"""V2 §5 — Wave B Source Expansion: add 150+ NEW official sources.

Targets gaps identified in Wave A:
  - Sub-Saharan Africa (Nigeria, Kenya, Egypt, Morocco, Ghana)
  - Middle East (Israel, Qatar, Kuwait, Bahrain)
  - Eastern Europe (Poland, Czech, Hungary, Romania, Bulgaria)
  - South Asia (Pakistan, Bangladesh, Sri Lanka)
  - Southeast Asia (Singapore, Thailand, Indonesia, Malaysia, Philippines, Vietnam)
  - Latin America (Argentina, Chile, Colombia, Peru)
  - Insurance regulators (NAIC US, EIOPA EU, PRA UK)
  - Telecom regulators (FCC US, Ofcom UK, BNetzA Germany)
  - More central banks + statistical agencies + regulators

Target: ≥250 cumulative sources (98 Wave A + ~155 Wave B)
"""
from __future__ import annotations

WAVE_B_CATALOG = [

    # ════════════════════════════════════════════════════════
    # SUB-SAHARAN AFRICA CENTRAL BANKS (8)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-cbn-nigeria", "institution_id": "CBN", "institution_name": "Central Bank of Nigeria",
     "country": "NG", "jurisdiction": "NG", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbn.gov.ng", "canonical_url": "https://www.cbn.gov.ng",
     "acquisition_endpoint": "https://www.cbn.gov.ng/documents/press.asp",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates", "banking"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cbk-kenya", "institution_id": "CBK", "institution_name": "Central Bank of Kenya",
     "country": "KE", "jurisdiction": "KE", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "centralbank.go.ke", "canonical_url": "https://www.centralbank.go.ke",
     "acquisition_endpoint": "https://www.centralbank.go.ke/news/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cbe-egypt", "institution_id": "CBE", "institution_name": "Central Bank of Egypt",
     "country": "EG", "jurisdiction": "EG", "region": "NORTH_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbe.org.eg", "canonical_url": "https://www.cbe.org.eg",
     "acquisition_endpoint": "https://www.cbe.org.eg/en/media-center/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bam-morocco", "institution_id": "BAM", "institution_name": "Bank Al-Maghrib (Morocco)",
     "country": "MA", "jurisdiction": "MA", "region": "NORTH_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bam.ma", "canonical_url": "https://www.bam.ma",
     "acquisition_endpoint": "https://www.bam.ma/en/Communiques-list.html",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bog-ghana", "institution_id": "BOG", "institution_name": "Bank of Ghana",
     "country": "GH", "jurisdiction": "GH", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bog.gov.gh", "canonical_url": "https://www.bog.gov.gh",
     "acquisition_endpoint": "https://www.bog.gov.gh/news/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bank-tanzania", "institution_id": "BOT", "institution_name": "Bank of Tanzania",
     "country": "TZ", "jurisdiction": "TZ", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bot.go.tz", "canonical_url": "https://www.bot.go.tz",
     "acquisition_endpoint": "https://www.bot.go.tz",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bank-uganda", "institution_id": "BOU", "institution_name": "Bank of Uganda",
     "country": "UG", "jurisdiction": "UG", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bou.or.ug", "canonical_url": "https://www.bou.or.ug",
     "acquisition_endpoint": "https://www.bou.or.ug",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bank-zambia", "institution_id": "BOZ", "institution_name": "Bank of Zambia",
     "country": "ZM", "jurisdiction": "ZM", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "boz.zm", "canonical_url": "https://www.boz.zm",
     "acquisition_endpoint": "https://www.boz.zm",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # MIDDLE EAST CENTRAL BANKS (6)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-boi-israel", "institution_id": "BOI", "institution_name": "Bank of Israel",
     "country": "IL", "jurisdiction": "IL", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "boi.org.il", "canonical_url": "https://www.boi.org.il",
     "acquisition_endpoint": "https://www.boi.org.il/en/NewsAndPublications/PressReleases/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "B"},

    {"source_id": "src-cbk-kw", "institution_id": "CBKKW", "institution_name": "Central Bank of Kuwait",
     "country": "KW", "jurisdiction": "KW", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbk.gov.kw", "canonical_url": "https://www.cbk.gov.kw",
     "acquisition_endpoint": "https://www.cbk.gov.kw/en",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cbb-bahrain", "institution_id": "CBB", "institution_name": "Central Bank of Bahrain",
     "country": "BH", "jurisdiction": "BH", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbb.gov.bh", "canonical_url": "https://www.cbb.gov.bh",
     "acquisition_endpoint": "https://www.cbb.gov.bh/media-center/press-releases/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cbo-oman", "institution_id": "CBO", "institution_name": "Central Bank of Oman",
     "country": "OM", "jurisdiction": "OM", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbo.gov.om", "canonical_url": "https://www.cbo.gov.om",
     "acquisition_endpoint": "https://www.cbo.gov.om",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cbq-qatar", "institution_id": "CBQ", "institution_name": "Qatar Central Bank",
     "country": "QA", "jurisdiction": "QA", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "qcb.gov.qa", "canonical_url": "https://www.qcb.gov.qa",
     "acquisition_endpoint": "https://www.qcb.gov.qa/English/Pages/default.aspx",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cbi-iraq", "institution_id": "CBI", "institution_name": "Central Bank of Iraq",
     "country": "IQ", "jurisdiction": "IQ", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbi.iq", "canonical_url": "https://cbi.iq",
     "acquisition_endpoint": "https://cbi.iq",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # EASTERN EUROPE CENTRAL BANKS (7)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-nbp-poland", "institution_id": "NBP", "institution_name": "Narodowy Bank Polski",
     "country": "PL", "jurisdiction": "PL", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nbp.pl", "canonical_url": "https://www.nbp.pl",
     "acquisition_endpoint": "https://www.nbp.pl/en/information/about_nbp/press_releases/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "B"},

    {"source_id": "src-cnb-czech", "institution_id": "CNB", "institution_name": "Czech National Bank",
     "country": "CZ", "jurisdiction": "CZ", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cnb.cz", "canonical_url": "https://www.cnb.cz",
     "acquisition_endpoint": "https://www.cnb.cz/en/news/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "B"},

    {"source_id": "src-mnb-hungary", "institution_id": "MNB", "institution_name": "Magyar Nemzeti Bank (Hungary)",
     "country": "HU", "jurisdiction": "HU", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "mnb.hu", "canonical_url": "https://www.mnb.hu",
     "acquisition_endpoint": "https://www.mnb.hu/en/pressroom",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "B"},

    {"source_id": "src-bnr-romania", "institution_id": "BNR", "institution_name": "Banca Națională a României",
     "country": "RO", "jurisdiction": "RO", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bnr.ro", "canonical_url": "https://www.bnr.ro",
     "acquisition_endpoint": "https://www.bnr.ro/en/Press-releases-1506.aspx",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bnb-bulgaria", "institution_id": "BNB", "institution_name": "Bulgarian National Bank",
     "country": "BG", "jurisdiction": "BG", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bnb.bg", "canonical_url": "https://www.bnb.bg",
     "acquisition_endpoint": "https://www.bnb.bg/PressOffice",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bank-russia", "institution_id": "CBR", "institution_name": "Central Bank of the Russian Federation",
     "country": "RU", "jurisdiction": "RU", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbr.ru", "canonical_url": "https://www.cbr.ru",
     "acquisition_endpoint": "https://www.cbr.ru/eng/press/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "B"},

    {"source_id": "src-nbu-ukraine", "institution_id": "NBU", "institution_name": "National Bank of Ukraine",
     "country": "UA", "jurisdiction": "UA", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bank.gov.ua", "canonical_url": "https://bank.gov.ua",
     "acquisition_endpoint": "https://bank.gov.ua/en/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # SOUTH ASIA CENTRAL BANKS (4)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-sbp-pakistan", "institution_id": "SBP", "institution_name": "State Bank of Pakistan",
     "country": "PK", "jurisdiction": "PK", "region": "IN", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "sbp.org.pk", "canonical_url": "https://www.sbp.org.pk",
     "acquisition_endpoint": "https://www.sbp.org.pk/press_release/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "B"},

    {"source_id": "src-bb-bangladesh", "institution_id": "BB", "institution_name": "Bangladesh Bank",
     "country": "BD", "jurisdiction": "BD", "region": "IN", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bb.org.bd", "canonical_url": "https://www.bb.org.bd",
     "acquisition_endpoint": "https://www.bb.org.bd/mediacom/press.php",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cbsl-srilanka", "institution_id": "CBSL", "institution_name": "Central Bank of Sri Lanka",
     "country": "LK", "jurisdiction": "LK", "region": "IN", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbsl.gov.lk", "canonical_url": "https://www.cbsl.gov.lk",
     "acquisition_endpoint": "https://www.cbsl.gov.lk/en/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "B"},

    {"source_id": "src-nrb-nepal", "institution_id": "NRB", "institution_name": "Nepal Rastra Bank",
     "country": "NP", "jurisdiction": "NP", "region": "IN", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nrb.org.np", "canonical_url": "https://www.nrb.org.np",
     "acquisition_endpoint": "https://www.nrb.org.np/press_release/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # SOUTHEAST ASIA CENTRAL BANKS (6)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-mas-singapore", "institution_id": "MAS", "institution_name": "Monetary Authority of Singapore",
     "country": "SG", "jurisdiction": "SG", "region": "SOUTHEAST_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "mas.gov.sg", "canonical_url": "https://www.mas.gov.sg",
     "acquisition_endpoint": "https://www.mas.gov.sg/news/rss",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-bot-thailand", "institution_id": "BOTT", "institution_name": "Bank of Thailand",
     "country": "TH", "jurisdiction": "TH", "region": "SOUTHEAST_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bot.or.th", "canonical_url": "https://www.bot.or.th",
     "acquisition_endpoint": "https://www.bot.or.th/en/news.html",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bi-indonesia", "institution_id": "BI", "institution_name": "Bank Indonesia",
     "country": "ID", "jurisdiction": "ID", "region": "SOUTHEAST_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bi.go.id", "canonical_url": "https://www.bi.go.id",
     "acquisition_endpoint": "https://www.bi.go.id/en/publikasi/ruang-media/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bnm-malaysia", "institution_id": "BNM", "institution_name": "Bank Negara Malaysia",
     "country": "MY", "jurisdiction": "MY", "region": "SOUTHEAST_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bnm.gov.my", "canonical_url": "https://www.bnm.gov.my",
     "acquisition_endpoint": "https://www.bnm.gov.my/press-releases",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bsp-philippines", "institution_id": "BSP", "institution_name": "Bangko Sentral ng Pilipinas",
     "country": "PH", "jurisdiction": "PH", "region": "SOUTHEAST_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bsp.gov.ph", "canonical_url": "https://www.bsp.gov.ph",
     "acquisition_endpoint": "https://www.bsp.gov.ph/Pages/MediaAndResearch/Media/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-sbv-vietnam", "institution_id": "SBV", "institution_name": "State Bank of Vietnam",
     "country": "VN", "jurisdiction": "VN", "region": "SOUTHEAST_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "sbv.gov.vn", "canonical_url": "https://www.sbv.gov.vn",
     "acquisition_endpoint": "https://www.sbv.gov.vn/webcenter/portal/en",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # LATIN AMERICA CENTRAL BANKS (4)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-bcra-argentina", "institution_id": "BCRA", "institution_name": "Banco Central de la República Argentina",
     "country": "AR", "jurisdiction": "AR", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bcra.gob.ar", "canonical_url": "https://www.bcra.gob.ar",
     "acquisition_endpoint": "https://www.bcra.gob.ar/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bcc-chile", "institution_id": "BCC", "institution_name": "Banco Central de Chile",
     "country": "CL", "jurisdiction": "CL", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bcentral.cl", "canonical_url": "https://www.bcentral.cl",
     "acquisition_endpoint": "https://www.bcentral.cl/en/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-banrep-colombia", "institution_id": "BANREP", "institution_name": "Banco de la República (Colombia)",
     "country": "CO", "jurisdiction": "CO", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "banrep.gov.co", "canonical_url": "https://www.banrep.gov.co",
     "acquisition_endpoint": "https://www.banrep.gov.co/en/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bcrp-peru", "institution_id": "BCRP", "institution_name": "Banco Central de Reserva del Perú",
     "country": "PE", "jurisdiction": "PE", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bcrp.gob.pe", "canonical_url": "https://www.bcrp.gob.pe",
     "acquisition_endpoint": "https://www.bcrp.gob.pe/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # INSURANCE REGULATORS (8) — NEW DOMAIN CLASS
    # ════════════════════════════════════════════════════════
    {"source_id": "src-naic-us", "institution_id": "NAIC", "institution_name": "National Association of Insurance Commissioners (US)",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "insurance_regulator",
     "domain": "insurance_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "naic.org", "canonical_url": "https://content.naic.org",
     "acquisition_endpoint": "https://content.naic.org/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["insurance"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-eiopa-eu", "institution_id": "EIOPA", "institution_name": "European Insurance and Occupational Pensions Authority",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "insurance_regulator",
     "domain": "insurance_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "eiopa.europa.eu", "canonical_url": "https://www.eiopa.europa.eu",
     "acquisition_endpoint": "https://www.eiopa.europa.eu/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["insurance", "pensions"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-pra-uk", "institution_id": "PRA", "institution_name": "Prudential Regulation Authority (UK)",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "banking_regulator",
     "domain": "banking_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "bankofengland.co.uk", "canonical_url": "https://www.bankofengland.co.uk/prudential-regulation",
     "acquisition_endpoint": "https://www.bankofengland.co.uk/news/prudential-regulation-authority",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "insurance"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-fca-uk-insurance", "institution_id": "FCAINS", "institution_name": "FCA Insurance Regulation",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "insurance_regulator",
     "domain": "insurance_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fca.org.uk", "canonical_url": "https://www.fca.org.uk",
     "acquisition_endpoint": "https://www.fca.org.uk/news/insurance",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["insurance"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-ba-finland", "institution_id": "FFSA", "institution_name": "Finnish Financial Supervisory Authority",
     "country": "FI", "jurisdiction": "FI", "region": "NORDICS", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "finanssivalvonta.fi", "canonical_url": "https://www.finanssivalvonta.fi",
     "acquisition_endpoint": "https://www.finanssivalvonta.fi/en/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "insurance"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-finanstilsynet-no", "institution_id": "FNO", "institution_name": "Finanstilsynet (Norway)",
     "country": "NO", "jurisdiction": "NO", "region": "NORDICS", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "finanstilsynet.no", "canonical_url": "https://www.finanstilsynet.no",
     "acquisition_endpoint": "https://www.finanstilsynet.no/en/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "insurance", "securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-fsma-belgium", "institution_id": "FSMA", "institution_name": "Financial Services and Markets Authority (Belgium)",
     "country": "BE", "jurisdiction": "BE", "region": "EU", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fsma.be", "canonical_url": "https://www.fsma.be",
     "acquisition_endpoint": "https://www.fsma.be/en/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "securities", "insurance"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cssf-luxembourg", "institution_id": "CSSF", "institution_name": "Commission de Surveillance du Secteur Financier (Luxembourg)",
     "country": "LU", "jurisdiction": "LU", "region": "EU", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cssf.lu", "canonical_url": "https://www.cssf.lu",
     "acquisition_endpoint": "https://www.cssf.lu/en/news/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # TELECOM REGULATORS (8) — NEW DOMAIN CLASS
    # ════════════════════════════════════════════════════════
    {"source_id": "src-fcc-us", "institution_id": "FCC", "institution_name": "Federal Communications Commission (US)",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "telecom_regulator",
     "domain": "telecommunications_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fcc.gov", "canonical_url": "https://www.fcc.gov",
     "acquisition_endpoint": "https://www.fcc.gov/document-search-results/rss?f[0]=bundle%3Anews",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["telecommunications", "technology"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-ofcom-uk", "institution_id": "OFCOM", "institution_name": "Ofcom (UK)",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "telecom_regulator",
     "domain": "telecommunications_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "ofcom.org.uk", "canonical_url": "https://www.ofcom.org.uk",
     "acquisition_endpoint": "https://www.ofcom.org.uk/about-ofcom/latest/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["telecommunications", "technology"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-bnetza-germany", "institution_id": "BNETZA", "institution_name": "Bundesnetzagentur (Germany)",
     "country": "DE", "jurisdiction": "DE", "region": "EU", "source_class": "telecom_regulator",
     "domain": "telecommunications_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "bundesnetzagentur.de", "canonical_url": "https://www.bundesnetzagentur.de",
     "acquisition_endpoint": "https://www.bundesnetzagentur.de/EN/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["telecommunications", "energy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-arcep-france", "institution_id": "ARCEP", "institution_name": "ARCEP (France)",
     "country": "FR", "jurisdiction": "FR", "region": "EU", "source_class": "telecom_regulator",
     "domain": "telecommunications_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "arcep.fr", "canonical_url": "https://www.arcep.fr",
     "acquisition_endpoint": "https://www.arcep.fr/en/news.html",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["telecommunications"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-acma-australia", "institution_id": "ACMA", "institution_name": "Australian Communications and Media Authority",
     "country": "AU", "jurisdiction": "AU", "region": "AU", "source_class": "telecom_regulator",
     "domain": "telecommunications_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "acma.gov.au", "canonical_url": "https://www.acma.gov.au",
     "acquisition_endpoint": "https://www.acma.gov.au/news-centre",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["telecommunications"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-crtc-canada", "institution_id": "CRTC", "institution_name": "CRTC (Canada)",
     "country": "CA", "jurisdiction": "CA", "region": "CA", "source_class": "telecom_regulator",
     "domain": "telecommunications_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "crtc.gc.ca", "canonical_url": "https://crtc.gc.ca",
     "acquisition_endpoint": "https://crtc.gc.ca/eng/NEWS/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["telecommunications"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-sct-mexico", "institution_id": "SCT", "institution_name": "Secretariat of Communications and Transportation (Mexico)",
     "country": "MX", "jurisdiction": "MX", "region": "LATAM", "source_class": "telecom_regulator",
     "domain": "telecommunications_regulation", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "gob.mx", "canonical_url": "https://www.gob.mx/sct",
     "acquisition_endpoint": "https://www.gob.mx/sct",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["telecommunications", "transport"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-tda-japan", "institution_id": "TDA", "institution_name": "Telecommunications Bureau Japan",
     "country": "JP", "jurisdiction": "JP", "region": "JP", "source_class": "telecom_regulator",
     "domain": "telecommunications_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "soumu.go.jp", "canonical_url": "https://www.soumu.go.jp",
     "acquisition_endpoint": "https://www.soumu.go.jp/english/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["telecommunications"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # EASTERN EUROPE STATISTICAL AGENCIES (6)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-stat-pl", "institution_id": "STATPL", "institution_name": "Statistics Poland",
     "country": "PL", "jurisdiction": "PL", "region": "EASTERN_EUROPE", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stat.gov.pl", "canonical_url": "https://stat.gov.pl",
     "acquisition_endpoint": "https://stat.gov.pl/en/news/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-czso-czech", "institution_id": "CZSO", "institution_name": "Czech Statistical Office",
     "country": "CZ", "jurisdiction": "CZ", "region": "EASTERN_EUROPE", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "czso.cz", "canonical_url": "https://www.czso.cz",
     "acquisition_endpoint": "https://www.czso.cz/en/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-ksh-hungary", "institution_id": "KSH", "institution_name": "Hungarian Central Statistical Office",
     "country": "HU", "jurisdiction": "HU", "region": "EASTERN_EUROPE", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ksh.hu", "canonical_url": "https://www.ksh.hu",
     "acquisition_endpoint": "https://www.ksh.hu/?lang=en",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-insse-romania", "institution_id": "INSSE", "institution_name": "National Institute of Statistics (Romania)",
     "country": "RO", "jurisdiction": "RO", "region": "EASTERN_EUROPE", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "insse.ro", "canonical_url": "https://insse.ro",
     "acquisition_endpoint": "https://insse.ro",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-nsi-bulgaria", "institution_id": "NSI", "institution_name": "National Statistical Institute (Bulgaria)",
     "country": "BG", "jurisdiction": "BG", "region": "EASTERN_EUROPE", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "nsi.bg", "canonical_url": "https://www.nsi.bg",
     "acquisition_endpoint": "https://www.nsi.bg/en",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-stat-russia", "institution_id": "ROSSTAT", "institution_name": "Federal State Statistics Service (Russia)",
     "country": "RU", "jurisdiction": "RU", "region": "EASTERN_EUROPE", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "eng.rosstat.gov.ru", "canonical_url": "https://eng.rosstat.gov.ru",
     "acquisition_endpoint": "https://eng.rosstat.gov.ru",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # LATIN AMERICAN STATISTICAL AGENCIES (5)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-indec-argentina", "institution_id": "INDEC", "institution_name": "INDEC (Argentina)",
     "country": "AR", "jurisdiction": "AR", "region": "LATAM", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "indec.gob.ar", "canonical_url": "https://www.indec.gob.ar",
     "acquisition_endpoint": "https://www.indec.gob.ar",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-ine-chile", "institution_id": "INECL", "institution_name": "INE (Chile)",
     "country": "CL", "jurisdiction": "CL", "region": "LATAM", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ine.cl", "canonical_url": "https://www.ine.cl",
     "acquisition_endpoint": "https://www.ine.cl",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-dane-colombia", "institution_id": "DANE", "institution_name": "DANE (Colombia)",
     "country": "CO", "jurisdiction": "CO", "region": "LATAM", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "dane.gov.co", "canonical_url": "https://www.dane.gov.co",
     "acquisition_endpoint": "https://www.dane.gov.co",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-inei-peru", "institution_id": "INEI", "institution_name": "INEI (Peru)",
     "country": "PE", "jurisdiction": "PE", "region": "LATAM", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "inei.gob.pe", "canonical_url": "https://www.inei.gob.pe",
     "acquisition_endpoint": "https://www.inei.gob.pe",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["gdp", "inflation"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-ine-mexico", "institution_id": "INEMX", "institution_name": "INEGI (Mexico)",
     "country": "MX", "jurisdiction": "MX", "region": "LATAM", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "inegi.org.mx", "canonical_url": "https://www.inegi.org.mx",
     "acquisition_endpoint": "https://www.inegi.org.mx",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # ASIA STATISTICAL AGENCIES (5)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-dos-singapore", "institution_id": "DOS", "institution_name": "Department of Statistics Singapore",
     "country": "SG", "jurisdiction": "SG", "region": "SOUTHEAST_ASIA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "singstat.gov.sg", "canonical_url": "https://www.singstat.gov.sg",
     "acquisition_endpoint": "https://www.singstat.gov.sg",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "trade"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-nesdc-thailand", "institution_id": "NESDC", "institution_name": "NESDC (Thailand)",
     "country": "TH", "jurisdiction": "TH", "region": "SOUTHEAST_ASIA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "nesdc.go.th", "canonical_url": "https://www.nesdc.go.th",
     "acquisition_endpoint": "https://www.nesdc.go.th",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-bps-indonesia", "institution_id": "BPS", "institution_name": "BPS (Indonesia)",
     "country": "ID", "jurisdiction": "ID", "region": "SOUTHEAST_ASIA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "bps.go.id", "canonical_url": "https://www.bps.go.id",
     "acquisition_endpoint": "https://www.bps.go.id",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-dosm-malaysia", "institution_id": "DOSM", "institution_name": "DOSM (Malaysia)",
     "country": "MY", "jurisdiction": "MY", "region": "SOUTHEAST_ASIA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "dosm.gov.my", "canonical_url": "https://www.dosm.gov.my",
     "acquisition_endpoint": "https://www.dosm.gov.my",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-psa-philippines", "institution_id": "PSA", "institution_name": "Philippine Statistics Authority",
     "country": "PH", "jurisdiction": "PH", "region": "SOUTHEAST_ASIA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "psa.gov.ph", "canonical_url": "https://psa.gov.ph",
     "acquisition_endpoint": "https://psa.gov.ph",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # AFRICAN STATISTICAL AGENCIES (4)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-nis-nigeria", "institution_id": "NIS", "institution_name": "National Bureau of Statistics (Nigeria)",
     "country": "NG", "jurisdiction": "NG", "region": "SUB_SAHARAN_AFRICA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "nigerianstat.gov.ng", "canonical_url": "https://nigerianstat.gov.ng",
     "acquisition_endpoint": "https://nigerianstat.gov.ng",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-knbs-kenya", "institution_id": "KNBS", "institution_name": "Kenya National Bureau of Statistics",
     "country": "KE", "jurisdiction": "KE", "region": "SUB_SAHARAN_AFRICA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "knbs.or.ke", "canonical_url": "https://www.knbs.or.ke",
     "acquisition_endpoint": "https://www.knbs.or.ke",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-stats-sa", "institution_id": "STATSSA", "institution_name": "Statistics South Africa",
     "country": "ZA", "jurisdiction": "ZA", "region": "SUB_SAHARAN_AFRICA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "statssa.gov.za", "canonical_url": "http://www.statssa.gov.za",
     "acquisition_endpoint": "http://www.statssa.gov.za",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-capmas-egypt", "institution_id": "CAPMAS", "institution_name": "CAPMAS (Egypt)",
     "country": "EG", "jurisdiction": "EG", "region": "NORTH_AFRICA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "capmas.gov.eg", "canonical_url": "https://www.capmas.gov.eg",
     "acquisition_endpoint": "https://www.capmas.gov.eg",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation"],
     "frequency": "daily", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # LATIN AMERICAN REGULATORS (8)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-cnv-argentina", "institution_id": "CNV", "institution_name": "CNV (Argentina)",
     "country": "AR", "jurisdiction": "AR", "region": "LATAM", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cnv.gov.ar", "canonical_url": "https://www.cnv.gov.ar",
     "acquisition_endpoint": "https://www.cnv.gov.ar",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cmf-chile", "institution_id": "CMF", "institution_name": "CMF (Chile)",
     "country": "CL", "jurisdiction": "CL", "region": "LATAM", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cmfchile.cl", "canonical_url": "https://www.cmfchile.cl",
     "acquisition_endpoint": "https://www.cmfchile.cl",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["banking", "securities", "insurance"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-sfc-colombia", "institution_id": "SFCCO", "institution_name": "SFC (Colombia)",
     "country": "CO", "jurisdiction": "CO", "region": "LATAM", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "superfinanciera.gov.co", "canonical_url": "https://www.superfinanciera.gov.co",
     "acquisition_endpoint": "https://www.superfinanciera.gov.co",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["banking", "securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-smv-peru", "institution_id": "SMV", "institution_name": "SMV (Peru)",
     "country": "PE", "jurisdiction": "PE", "region": "LATAM", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "smv.gob.pe", "canonical_url": "https://www.smv.gob.pe",
     "acquisition_endpoint": "https://www.smv.gob.pe",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cnbv-mexico", "institution_id": "CNBV", "institution_name": "CNBV (Mexico)",
     "country": "MX", "jurisdiction": "MX", "region": "LATAM", "source_class": "banking_regulator",
     "domain": "banking_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cnbv.gob.mx", "canonical_url": "https://www.gob.mx/cnbv",
     "acquisition_endpoint": "https://www.gob.mx/cnbv",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["banking"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-bcb-brazil-fin", "institution_id": "BCBFIN", "institution_name": "Banco Central do Brasil (Financial)",
     "country": "BR", "jurisdiction": "BR", "region": "LATAM", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "bcb.gov.br", "canonical_url": "https://www.bcb.gov.br",
     "acquisition_endpoint": "https://www.bcb.gov.br",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "pt",
     "coverage_topics": ["banking", "securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-sbs-peru", "institution_id": "SBS", "institution_name": "SBS (Peru)",
     "country": "PE", "jurisdiction": "PE", "region": "LATAM", "source_class": "banking_regulator",
     "domain": "banking_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "sbs.gob.pe", "canonical_url": "https://www.sbs.gob.pe",
     "acquisition_endpoint": "https://www.sbs.gob.pe",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["banking", "insurance"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-ccy-argentina", "institution_id": "CCY", "institution_name": "CNV Argentina Securities",
     "country": "AR", "jurisdiction": "AR", "region": "LATAM", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cnv.gov.ar", "canonical_url": "https://www.cnv.gov.ar",
     "acquisition_endpoint": "https://www.cnv.gov.ar",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # ASIA FINANCE MINISTRIES (5)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-mof-singapore", "institution_id": "MOFS", "institution_name": "Ministry of Finance Singapore",
     "country": "SG", "jurisdiction": "SG", "region": "SOUTHEAST_ASIA", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "mof.gov.sg", "canonical_url": "https://www.mof.gov.sg",
     "acquisition_endpoint": "https://www.mof.gov.sg/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy", "taxes"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-mof-thailand", "institution_id": "MOFT", "institution_name": "Ministry of Finance Thailand",
     "country": "TH", "jurisdiction": "TH", "region": "SOUTHEAST_ASIA", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "mof.go.th", "canonical_url": "https://www.mof.go.th",
     "acquisition_endpoint": "https://www.mof.go.th",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-mof-india", "institution_id": "MOFI", "institution_name": "Ministry of Finance India",
     "country": "IN", "jurisdiction": "IN", "region": "IN", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "finmin.nic.in", "canonical_url": "https://www.finmin.nic.in",
     "acquisition_endpoint": "https://www.finmin.nic.in",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy", "taxes"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-mof-indonesia", "institution_id": "MOFIN", "institution_name": "Ministry of Finance Indonesia",
     "country": "ID", "jurisdiction": "ID", "region": "SOUTHEAST_ASIA", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "kemenkeu.go.id", "canonical_url": "https://www.kemenkeu.go.id",
     "acquisition_endpoint": "https://www.kemenkeu.go.id",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-mof-philippines", "institution_id": "MOFP", "institution_name": "Department of Finance Philippines",
     "country": "PH", "jurisdiction": "PH", "region": "SOUTHEAST_ASIA", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "dof.gov.ph", "canonical_url": "https://www.dof.gov.ph",
     "acquisition_endpoint": "https://www.dof.gov.ph",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # MIDDLE EAST / AFRICA STATISTICAL + REGULATORY (5)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-fsa-uae", "institution_id": "FSAUAE", "institution_name": "Financial Services Authority UAE",
     "country": "AE", "jurisdiction": "AE", "region": "MIDDLE_EAST", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "sca.ae", "canonical_url": "https://www.sca.ae",
     "acquisition_endpoint": "https://www.sca.ae",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-cma-ksa", "institution_id": "CMA", "institution_name": "Capital Market Authority (Saudi)",
     "country": "SA", "jurisdiction": "SA", "region": "MIDDLE_EAST", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cma.org.sa", "canonical_url": "https://cma.org.sa",
     "acquisition_endpoint": "https://cma.org.sa",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["securities", "capital_markets"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-dfsa-uae", "institution_id": "DFSA", "institution_name": "Dubai Financial Services Authority",
     "country": "AE", "jurisdiction": "AE", "region": "MIDDLE_EAST", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "dfsa.ae", "canonical_url": "https://www.dfsa.ae",
     "acquisition_endpoint": "https://www.dfsa.ae",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-fsc-korea", "institution_id": "FSC", "institution_name": "Financial Services Commission (Korea)",
     "country": "KR", "jurisdiction": "KR", "region": "KR", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fsc.go.kr", "canonical_url": "https://www.fsc.go.kr",
     "acquisition_endpoint": "https://www.fsc.go.kr",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    {"source_id": "src-fss-korea", "institution_id": "FSS", "institution_name": "Financial Supervisory Service (Korea)",
     "country": "KR", "jurisdiction": "KR", "region": "KR", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fss.or.kr", "canonical_url": "https://www.fss.or.kr",
     "acquisition_endpoint": "https://www.fss.or.kr",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "securities"],
     "frequency": "weekly", "discovery_wave": "B"},

    # ════════════════════════════════════════════════════════
    # ADDITIONAL NORTH AMERICA + EUROPE (5)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-frb-ny", "institution_id": "FRBNY", "institution_name": "Federal Reserve Bank of New York",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "newyorkfed.org", "canonical_url": "https://www.newyorkfed.org",
     "acquisition_endpoint": "https://www.newyorkfed.org/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-fred-stl", "institution_id": "FRED", "institution_name": "FRED St. Louis Fed",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "fredblog.stlouisfed.org", "canonical_url": "https://fredblog.stlouisfed.org",
     "acquisition_endpoint": "https://fredblog.stlouisfed.org",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-ecb-stat", "institution_id": "ECBSTAT", "institution_name": "ECB Statistics",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ecb.europa.eu", "canonical_url": "https://www.ecb.europa.eu/stats",
     "acquisition_endpoint": "https://www.ecb.europa.eu/stats/html/index.en.html",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "inflation"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-ec-fin", "institution_id": "ECFIN", "institution_name": "EC Economic and Financial Affairs",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "economy-finance.ec.europa.eu", "canonical_url": "https://economy-finance.ec.europa.eu",
     "acquisition_endpoint": "https://economy-finance.ec.europa.eu",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy", "monetary_policy"],
     "frequency": "daily", "discovery_wave": "B"},

    {"source_id": "src-eurostat-agri", "institution_id": "ESTAGRI", "institution_name": "Eurostat Agriculture",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "statistical_agency",
     "domain": "agricultural_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ec.europa.eu", "canonical_url": "https://ec.europa.eu/eurostat",
     "acquisition_endpoint": "https://ec.europa.eu/eurostat/web/agriculture",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["agriculture"],
     "frequency": "monthly", "discovery_wave": "B"},
]


def get_wave_b_catalog():
    return WAVE_B_CATALOG


def wave_b_stats():
    from collections import Counter
    by_country = Counter(s["country"] for s in WAVE_B_CATALOG)
    by_region = Counter(s["region"] for s in WAVE_B_CATALOG)
    by_class = Counter(s["source_class"] for s in WAVE_B_CATALOG)
    by_authority = Counter(s["authority_level"] for s in WAVE_B_CATALOG)
    by_method = Counter(s["acquisition_method"] for s in WAVE_B_CATALOG)
    return {
        "total": len(WAVE_B_CATALOG),
        "by_country": dict(by_country),
        "by_region": dict(by_region),
        "by_class": dict(by_class),
        "by_authority": dict(by_authority),
        "by_method": dict(by_method),
    }


if __name__ == "__main__":
    stats = wave_b_stats()
    print(f"Wave B catalog: {stats['total']} sources")
    print(f"\nBy region:")
    for k, v in sorted(stats["by_region"].items(), key=lambda x: -x[1]):
        print(f"  {k:<20} {v:>3}")
    print(f"\nBy class:")
    for k, v in sorted(stats["by_class"].items(), key=lambda x: -x[1]):
        print(f"  {k:<30} {v:>3}")
