"""ROUAA Global Official Source Network — Discovery Catalog.

A curated catalog of 100+ official sources across:
  - 40+ domain classes (financial, economic, regulatory, trade, energy, etc.)
  - 18+ geographic regions
  - Multiple authority levels
  - Multiple acquisition methods

This is the WAVE A discovery target per EXECUTION DIRECTIVE — GLOBAL OFFICIAL
SOURCE EXPANSION V1 §10.

Each entry is a dict that can be passed to SourceRecord(**entry).
"""
from __future__ import annotations


# Helper to generate source_id
def sid(inst_id: str) -> str:
    return f"src-{inst_id.lower().replace(' ', '-').replace('.', '-')[:40]}"


# ── WAVE A: 100+ official sources across all domains ──

DISCOVERY_CATALOG = [

    # ════════════════════════════════════════════════════════
    # CENTRAL BANKS & MONETARY AUTHORITIES (15)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-fed-reserve", "institution_id": "FED", "institution_name": "Federal Reserve System",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "federalreserve.gov", "canonical_url": "https://www.federalreserve.gov",
     "acquisition_endpoint": "https://www.federalreserve.gov/feeds/press_all.xml",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates", "banking"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-ecb", "institution_id": "ECB", "institution_name": "European Central Bank",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "ecb.europa.eu", "canonical_url": "https://www.ecb.europa.eu",
     "acquisition_endpoint": "https://www.ecb.europa.eu/rss/press.html",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates", "inflation"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-boe", "institution_id": "BOE", "institution_name": "Bank of England",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bankofengland.co.uk", "canonical_url": "https://www.bankofengland.co.uk",
     "acquisition_endpoint": "https://www.bankofengland.co.uk/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates", "banking"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-boj", "institution_id": "BOJ", "institution_name": "Bank of Japan",
     "country": "JP", "jurisdiction": "JP", "region": "JP", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "boj.or.jp", "canonical_url": "https://www.boj.or.jp/en/",
     "acquisition_endpoint": "https://www.boj.or.jp/en/", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-pboc", "institution_id": "PBOC", "institution_name": "People's Bank of China",
     "country": "CN", "jurisdiction": "CN", "region": "CN", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "pbc.gov.cn", "canonical_url": "http://www.pbc.gov.cn",
     "acquisition_endpoint": "http://www.pbc.gov.cn", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "zh",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-snb", "institution_id": "SNB", "institution_name": "Swiss National Bank",
     "country": "CH", "jurisdiction": "CH", "region": "EU", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "snb.ch", "canonical_url": "https://www.snb.ch",
     "acquisition_endpoint": "https://www.snb.ch", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-boc", "institution_id": "BOC", "institution_name": "Bank of Canada",
     "country": "CA", "jurisdiction": "CA", "region": "CA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bankofcanada.ca", "canonical_url": "https://www.bankofcanada.ca",
     "acquisition_endpoint": "https://www.bankofcanada.ca", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-rba", "institution_id": "RBA", "institution_name": "Reserve Bank of Australia",
     "country": "AU", "jurisdiction": "AU", "region": "AU", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "rba.gov.au", "canonical_url": "https://www.rba.gov.au",
     "acquisition_endpoint": "https://www.rba.gov.au/rss/rss-cb-media.html",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-rbnz", "institution_id": "RBNZ", "institution_name": "Reserve Bank of New Zealand",
     "country": "NZ", "jurisdiction": "NZ", "region": "NZ", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "rbnz.govt.nz", "canonical_url": "https://www.rbnz.govt.nz",
     "acquisition_endpoint": "https://www.rbnz.govt.nz", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-riksbank", "institution_id": "RIKSBANK", "institution_name": "Sveriges Riksbank",
     "country": "SE", "jurisdiction": "SE", "region": "NORDICS", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "riksbank.se", "canonical_url": "https://www.riksbank.se",
     "acquisition_endpoint": "https://www.riksbank.se/en-gb/press-and-published/rss/",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-norges", "institution_id": "NB", "institution_name": "Norges Bank",
     "country": "NO", "jurisdiction": "NO", "region": "NORDICS", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "norges-bank.no", "canonical_url": "https://www.norges-bank.no",
     "acquisition_endpoint": "https://www.norges-bank.no/en/news/", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-bundesbank", "institution_id": "BBK", "institution_name": "Deutsche Bundesbank",
     "country": "DE", "jurisdiction": "DE", "region": "EU", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bundesbank.de", "canonical_url": "https://www.bundesbank.de",
     "acquisition_endpoint": "https://www.bundesbank.de/en/rss-feeds", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-bankitaly", "institution_id": "BDI", "institution_name": "Banca d'Italia",
     "country": "IT", "jurisdiction": "IT", "region": "EU", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bancaditalia.it", "canonical_url": "https://www.bancaditalia.it",
     "acquisition_endpoint": "https://www.bancaditalia.it", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-banque-france", "institution_id": "BDF", "institution_name": "Banque de France",
     "country": "FR", "jurisdiction": "FR", "region": "EU", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "banque-france.fr", "canonical_url": "https://www.banque-france.fr",
     "acquisition_endpoint": "https://www.banque-france.fr/en/rss.xml", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-brazil-bcb", "institution_id": "BCB", "institution_name": "Banco Central do Brasil",
     "country": "BR", "jurisdiction": "BR", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bcb.gov.br", "canonical_url": "https://www.bcb.gov.br",
     "acquisition_endpoint": "https://www.bcb.gov.br", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "pt",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # STATISTICAL AGENCIES (12)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-bea", "institution_id": "BEA", "institution_name": "Bureau of Economic Analysis",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "bea.gov", "canonical_url": "https://www.bea.gov",
     "acquisition_endpoint": "https://www.bea.gov/news?format=feed", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["gdp", "employment", "trade"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-bls", "institution_id": "BLS", "institution_name": "Bureau of Labor Statistics",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "statistical_agency",
     "domain": "labor_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "bls.gov", "canonical_url": "https://www.bls.gov",
     "acquisition_endpoint": "https://www.bls.gov/feed/release.rss", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["employment", "inflation"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-census", "institution_id": "CENSUS", "institution_name": "US Census Bureau",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "statistical_agency",
     "domain": "demographic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "census.gov", "canonical_url": "https://www.census.gov",
     "acquisition_endpoint": "https://www.census.gov/newsroom/rss-feeds.html", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["trade", "housing", "manufacturing"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-eurostat", "institution_id": "ESTAT", "institution_name": "Eurostat",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ec.europa.eu", "canonical_url": "https://ec.europa.eu/eurostat",
     "acquisition_endpoint": "https://ec.europa.eu/eurostat/web/main/news", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment", "trade"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-ons", "institution_id": "ONS", "institution_name": "Office for National Statistics (UK)",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ons.gov.uk", "canonical_url": "https://www.ons.gov.uk",
     "acquisition_endpoint": "https://www.ons.gov.uk/news", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-statcan", "institution_id": "STATCAN", "institution_name": "Statistics Canada",
     "country": "CA", "jurisdiction": "CA", "region": "CA", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "statcan.gc.ca", "canonical_url": "https://www.statcan.gc.ca",
     "acquisition_endpoint": "https://www.statcan.gc.ca/en/rss", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["gdp", "employment", "trade"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-abs", "institution_id": "ABS", "institution_name": "Australian Bureau of Statistics",
     "country": "AU", "jurisdiction": "AU", "region": "AU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "abs.gov.au", "canonical_url": "https://www.abs.gov.au",
     "acquisition_endpoint": "https://www.abs.gov.au/rss", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-statsnz", "institution_id": "STATSNZ", "institution_name": "Stats NZ",
     "country": "NZ", "jurisdiction": "NZ", "region": "NZ", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stats.govt.nz", "canonical_url": "https://www.stats.govt.nz",
     "acquisition_endpoint": "https://www.stats.govt.nz", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-statjapan", "institution_id": "SJ", "institution_name": "Statistics Bureau of Japan",
     "country": "JP", "jurisdiction": "JP", "region": "JP", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stat.go.jp", "canonical_url": "https://www.stat.go.jp",
     "acquisition_endpoint": "https://www.stat.go.jp", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "monthly", "discovery_wave": "A"},

    {"source_id": "src-statschina", "institution_id": "NBS", "institution_name": "National Bureau of Statistics of China",
     "country": "CN", "jurisdiction": "CN", "region": "CN", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stats.gov.cn", "canonical_url": "http://www.stats.gov.cn",
     "acquisition_endpoint": "http://www.stats.gov.cn", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "zh",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "monthly", "discovery_wave": "A"},

    {"source_id": "src-destatis", "institution_id": "DEST", "institution_name": "Destatis (Germany)",
     "country": "DE", "jurisdiction": "DE", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "destatis.de", "canonical_url": "https://www.destatis.de",
     "acquisition_endpoint": "https://www.destatis.de/EN/Service/RSS/_functionsliste.xml",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-istat", "institution_id": "ISTAT", "institution_name": "Istat (Italy)",
     "country": "IT", "jurisdiction": "IT", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "istat.it", "canonical_url": "https://www.istat.it",
     "acquisition_endpoint": "https://www.istat.it/en/rss", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "daily", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # FINANCIAL REGULATORS (15)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-sec", "institution_id": "SEC", "institution_name": "Securities and Exchange Commission",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "sec.gov", "canonical_url": "https://www.sec.gov",
     "acquisition_endpoint": "https://www.sec.gov/news/pressreleases.rss",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["securities", "corporate_regulation", "capital_markets"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-cftc", "institution_id": "CFTC", "institution_name": "Commodity Futures Trading Commission",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "financial_regulator",
     "domain": "derivatives_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cftc.gov", "canonical_url": "https://www.cftc.gov",
     "acquisition_endpoint": "https://www.cftc.gov/PressRoom/PressReleases",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["securities", "commodities"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-fca", "institution_id": "FCA", "institution_name": "Financial Conduct Authority",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fca.org.uk", "canonical_url": "https://www.fca.org.uk",
     "acquisition_endpoint": "https://www.fca.org.uk/news/rss.xml",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["banking", "securities", "consumer_finance"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-esma", "institution_id": "ESMA", "institution_name": "European Securities and Markets Authority",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "esma.europa.eu", "canonical_url": "https://www.esma.europa.eu",
     "acquisition_endpoint": "https://www.esma.europa.eu/rss.xml",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["securities", "capital_markets"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-consob", "institution_id": "CONSOB", "institution_name": "CONSOB (Italy)",
     "country": "IT", "jurisdiction": "IT", "region": "EU", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "consob.it", "canonical_url": "https://www.consob.it",
     "acquisition_endpoint": "https://www.consob.it", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["securities"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-amf-france", "institution_id": "AMF", "institution_name": "Autorité des marchés financiers (France)",
     "country": "FR", "jurisdiction": "FR", "region": "EU", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "amf-france.org", "canonical_url": "https://www.amf-france.org",
     "acquisition_endpoint": "https://www.amf-france.org/en/rss.xml", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["securities", "capital_markets"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-bafin", "institution_id": "BAFIN", "institution_name": "BaFin (Germany)",
     "country": "DE", "jurisdiction": "DE", "region": "EU", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "bafin.de", "canonical_url": "https://www.bafin.de",
     "acquisition_endpoint": "https://www.bafin.de/EN/RSS/_functionsliste.xml",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["banking", "securities", "insurance"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-finra", "institution_id": "FINRA", "institution_name": "FINRA",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "finra.org", "canonical_url": "https://www.finra.org",
     "acquisition_endpoint": "https://www.finra.org/newsroom/news-releases/feed",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["securities", "corporate_regulation"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-sfc-hk", "institution_id": "SFC", "institution_name": "Securities and Futures Commission (HK)",
     "country": "HK", "jurisdiction": "HK", "region": "CN", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "sfc.hk", "canonical_url": "https://www.sfc.hk",
     "acquisition_endpoint": "https://www.sfc.hk/en/News-and-announcements",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["securities", "capital_markets"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-fsa-japan", "institution_id": "FSA", "institution_name": "Financial Services Agency (Japan)",
     "country": "JP", "jurisdiction": "JP", "region": "JP", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fsa.go.jp", "canonical_url": "https://www.fsa.go.jp",
     "acquisition_endpoint": "https://www.fsa.go.jp", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "securities", "insurance"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-csa-canada", "institution_id": "CSA", "institution_name": "Canadian Securities Administrators",
     "country": "CA", "jurisdiction": "CA", "region": "CA", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "securities-administrators.ca", "canonical_url": "https://www.securities-administrators.ca",
     "acquisition_endpoint": "https://www.securities-administrators.ca", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["securities"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-cvm-brazil", "institution_id": "CVM", "institution_name": "Comissão de Valores Mobiliários (Brazil)",
     "country": "BR", "jurisdiction": "BR", "region": "LATAM", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "gov.br", "canonical_url": "https://www.gov.br/cvm",
     "acquisition_endpoint": "https://www.gov.br/cvm", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "pt",
     "coverage_topics": ["securities"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-asic-au", "institution_id": "ASIC", "institution_name": "ASIC (Australia)",
     "country": "AU", "jurisdiction": "AU", "region": "AU", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "asic.gov.au", "canonical_url": "https://asic.gov.au",
     "acquisition_endpoint": "https://asic.gov.au/about-asic/news-centre/find-a-news-story/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking", "securities", "consumer_finance"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-cysec-cy", "institution_id": "CYSEC", "institution_name": "CySEC (Cyprus)",
     "country": "CY", "jurisdiction": "CY", "region": "EU", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cysec.gov.cy", "canonical_url": "https://www.cysec.gov.cy",
     "acquisition_endpoint": "https://www.cysec.gov.cy/en-GB/rss-feed/",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["securities"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-fma-austria", "institution_id": "FMA", "institution_name": "FMA (Austria)",
     "country": "AT", "jurisdiction": "AT", "region": "EU", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fma.gv.at", "canonical_url": "https://www.fma.gv.at",
     "acquisition_endpoint": "https://www.fma.gv.at/en/news/rss-feed/",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["banking", "securities", "insurance"],
     "frequency": "weekly", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # STOCK EXCHANGES & MARKET OPERATORS (8)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-nyse", "institution_id": "NYSE", "institution_name": "New York Stock Exchange",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "stock_exchange",
     "domain": "market_data", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "nyse.com", "canonical_url": "https://www.nyse.com",
     "acquisition_endpoint": "https://www.nyse.com/news", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["capital_markets", "securities"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-nasdaq", "institution_id": "NASDAQ", "institution_name": "Nasdaq",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "stock_exchange",
     "domain": "market_data", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "nasdaq.com", "canonical_url": "https://www.nasdaq.com",
     "acquisition_endpoint": "https://www.nasdaq.com/news", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["capital_markets", "securities"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-lseg", "institution_id": "LSEG", "institution_name": "London Stock Exchange Group",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "stock_exchange",
     "domain": "market_data", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "londonstockexchange.com", "canonical_url": "https://www.londonstockexchange.com",
     "acquisition_endpoint": "https://www.londonstockexchange.com/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["capital_markets", "securities"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-euronext", "institution_id": "EURONEXT", "institution_name": "Euronext",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "stock_exchange",
     "domain": "market_data", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "euronext.com", "canonical_url": "https://www.euronext.com",
     "acquisition_endpoint": "https://www.euronext.com/en/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["capital_markets", "securities"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-deutsche-boerse", "institution_id": "DB", "institution_name": "Deutsche Börse",
     "country": "DE", "jurisdiction": "DE", "region": "EU", "source_class": "stock_exchange",
     "domain": "market_data", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "deutsche-boerse.com", "canonical_url": "https://www.deutsche-boerse.com",
     "acquisition_endpoint": "https://www.deutsche-boerse.com/dbg-en/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["capital_markets", "securities"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-jpx", "institution_id": "JPX", "institution_name": "Japan Exchange Group",
     "country": "JP", "jurisdiction": "JP", "region": "JP", "source_class": "stock_exchange",
     "domain": "market_data", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "jpx.co.jp", "canonical_url": "https://www.jpx.co.jp",
     "acquisition_endpoint": "https://www.jpx.co.jp", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["capital_markets"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-szse", "institution_id": "SZSE", "institution_name": "Shenzhen Stock Exchange",
     "country": "CN", "jurisdiction": "CN", "region": "CN", "source_class": "stock_exchange",
     "domain": "market_data", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "szse.cn", "canonical_url": "http://www.szse.cn",
     "acquisition_endpoint": "http://www.szse.cn", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "zh",
     "coverage_topics": ["capital_markets"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-b3-brazil", "institution_id": "B3", "institution_name": "B3 (Brazil)",
     "country": "BR", "jurisdiction": "BR", "region": "LATAM", "source_class": "stock_exchange",
     "domain": "market_data", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "b3.com.br", "canonical_url": "https://www.b3.com.br",
     "acquisition_endpoint": "https://www.b3.com.br", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["capital_markets"],
     "frequency": "daily", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # FINANCE MINISTRIES & TREASURIES (8)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-treasury-us", "institution_id": "TREAS", "institution_name": "US Department of the Treasury",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "home.treasury.gov", "canonical_url": "https://home.treasury.gov",
     "acquisition_endpoint": "https://home.treasury.gov/rss/press-releases",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["fiscal_policy", "public_debt", "taxes"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-hm-treasury", "institution_id": "HMT", "institution_name": "HM Treasury (UK)",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "gov.uk", "canonical_url": "https://www.gov.uk/government/organisations/hm-treasury",
     "acquisition_endpoint": "https://www.gov.uk/government/organisations/hm-treasury.atom",
     "endpoint_type": "ATOM", "acquisition_method": "ATOM", "language": "en",
     "coverage_topics": ["fiscal_policy", "taxes", "public_debt"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-mof-japan", "institution_id": "MOF", "institution_name": "Ministry of Finance (Japan)",
     "country": "JP", "jurisdiction": "JP", "region": "JP", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "mof.go.jp", "canonical_url": "https://www.mof.go.jp",
     "acquisition_endpoint": "https://www.mof.go.jp", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy", "public_debt"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-mof-china", "institution_id": "MOFCN", "institution_name": "Ministry of Finance (China)",
     "country": "CN", "jurisdiction": "CN", "region": "CN", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "mof.gov.cn", "canonical_url": "http://www.mof.gov.cn",
     "acquisition_endpoint": "http://www.mof.gov.cn", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "zh",
     "coverage_topics": ["fiscal_policy", "taxes"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-bmf-brazil", "institution_id": "BMF", "institution_name": "Ministério da Fazenda (Brazil)",
     "country": "BR", "jurisdiction": "BR", "region": "LATAM", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "gov.br", "canonical_url": "https://www.gov.br/fazenda",
     "acquisition_endpoint": "https://www.gov.br/fazenda", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "pt",
     "coverage_topics": ["fiscal_policy", "taxes"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-mef-italy", "institution_id": "MEF", "institution_name": "Ministero dell'Economia e delle Finanze (Italy)",
     "country": "IT", "jurisdiction": "IT", "region": "EU", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "mef.gov.it", "canonical_url": "https://www.mef.gov.it",
     "acquisition_endpoint": "https://www.mef.gov.it", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy", "public_debt"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-mef-france", "institution_id": "MEFFR", "institution_name": "Ministère de l'Économie et des Finances (France)",
     "country": "FR", "jurisdiction": "FR", "region": "EU", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "economie.gouv.fr", "canonical_url": "https://www.economie.gouv.fr",
     "acquisition_endpoint": "https://www.economie.gouv.fr", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "fr",
     "coverage_topics": ["fiscal_policy", "taxes"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-bmfca-canada", "institution_id": "BMFCA", "institution_name": "Department of Finance Canada",
     "country": "CA", "jurisdiction": "CA", "region": "CA", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "canada.ca", "canonical_url": "https://www.canada.ca/en/department-finance.html",
     "acquisition_endpoint": "https://www.canada.ca/en/department-finance.html",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["fiscal_policy", "taxes"],
     "frequency": "weekly", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # INTERNATIONAL INSTITUTIONS (10)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-imf", "institution_id": "IMF", "institution_name": "International Monetary Fund",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_financial_institution",
     "domain": "international_finance", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "imf.org", "canonical_url": "https://www.imf.org",
     "acquisition_endpoint": "https://www.imf.org/en/News/Search-Archive",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "trade", "external_sector"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-bis", "institution_id": "BIS", "institution_name": "Bank for International Settlements",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_financial_institution",
     "domain": "international_finance", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "bis.org", "canonical_url": "https://www.bis.org",
     "acquisition_endpoint": "https://www.bis.org/list/cbspubs/index.htm",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-worldbank", "institution_id": "WB", "institution_name": "World Bank Group",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_financial_institution",
     "domain": "development_finance", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "worldbank.org", "canonical_url": "https://www.worldbank.org",
     "acquisition_endpoint": "https://www.worldbank.org/en/news/rss",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["external_sector", "trade"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-oecd", "institution_id": "OECD", "institution_name": "OECD",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_economic_institution",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "oecd.org", "canonical_url": "https://www.oecd.org",
     "acquisition_endpoint": "https://www.oecd.org/newsroom/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "employment", "trade"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-wto", "institution_id": "WTO", "institution_name": "World Trade Organization",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_economic_institution",
     "domain": "trade", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "wto.org", "canonical_url": "https://www.wto.org",
     "acquisition_endpoint": "https://www.wto.org/english/news_e/news_e.xml",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["trade"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-fsb", "institution_id": "FSB", "institution_name": "Financial Stability Board",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_financial_institution",
     "domain": "financial_stability", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "fsb.org", "canonical_url": "https://www.fsb.org",
     "acquisition_endpoint": "https://www.fsb.org/feed/",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["banking", "capital_markets"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-ec", "institution_id": "EC", "institution_name": "European Commission",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "regional_economic_institution",
     "domain": "economic_policy", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "ec.europa.eu", "canonical_url": "https://ec.europa.eu",
     "acquisition_endpoint": "https://ec.europa.eu/commission/presscorner/api/rss",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["fiscal_policy", "trade", "competition"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-aadb", "institution_id": "ADB", "institution_name": "Asian Development Bank",
     "country": "INTL", "jurisdiction": "INTL", "region": "SOUTHEAST_ASIA", "source_class": "official_development_institution",
     "domain": "development_finance", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "adb.org", "canonical_url": "https://www.adb.org",
     "acquisition_endpoint": "https://www.adb.org/news/rss",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["external_sector", "trade"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-iadb", "institution_id": "IADB", "institution_name": "Inter-American Development Bank",
     "country": "INTL", "jurisdiction": "INTL", "region": "LATAM", "source_class": "official_development_institution",
     "domain": "development_finance", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "iadb.org", "canonical_url": "https://www.iadb.org",
     "acquisition_endpoint": "https://www.iadb.org/en/news/rss",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["external_sector"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-afrdb", "institution_id": "AFDB", "institution_name": "African Development Bank",
     "country": "INTL", "jurisdiction": "INTL", "region": "SUB_SAHARAN_AFRICA", "source_class": "official_development_institution",
     "domain": "development_finance", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "afdb.org", "canonical_url": "https://www.afdb.org",
     "acquisition_endpoint": "https://www.afdb.org/en/news-and-events/rss",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["external_sector"],
     "frequency": "weekly", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # ENERGY & COMMODITIES (8)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-eia-us", "institution_id": "EIA", "institution_name": "Energy Information Administration",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "energy_regulator",
     "domain": "energy_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "eia.gov", "canonical_url": "https://www.eia.gov",
     "acquisition_endpoint": "https://www.eia.gov/rss/", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["oil", "gas", "electricity", "renewables"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-ferc", "institution_id": "FERC", "institution_name": "Federal Energy Regulatory Commission",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "energy_regulator",
     "domain": "energy_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "ferc.gov", "canonical_url": "https://www.ferc.gov",
     "acquisition_endpoint": "https://www.ferc.gov/news-media/news-releases",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["electricity", "gas"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-iea", "institution_id": "IEA", "institution_name": "International Energy Agency",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_economic_institution",
     "domain": "energy_statistics", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "iea.org", "canonical_url": "https://www.iea.org",
     "acquisition_endpoint": "https://www.iea.org/news/rss",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["oil", "gas", "electricity", "renewables"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-opec", "institution_id": "OPEC", "institution_name": "OPEC",
     "country": "INTL", "jurisdiction": "INTL", "region": "MIDDLE_EAST", "source_class": "commodity_regulator",
     "domain": "oil_market", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "opec.org", "canonical_url": "https://www.opec.org",
     "acquisition_endpoint": "https://www.opec.org/opec_web/en/news_arss/",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["oil"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-beis-uk", "institution_id": "BEIS", "institution_name": "Department for Energy Security and Net Zero (UK)",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "energy_ministry",
     "domain": "energy_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "gov.uk", "canonical_url": "https://www.gov.uk/government/organisations/department-for-energy-security-and-net-zero",
     "acquisition_endpoint": "https://www.gov.uk/government/organisations/department-for-energy-security-and-net-zero.atom",
     "endpoint_type": "ATOM", "acquisition_method": "ATOM", "language": "en",
     "coverage_topics": ["energy", "renewables"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-bmwi-germany", "institution_id": "BMWIK", "institution_name": "Federal Ministry for Economic Affairs and Climate Action (Germany)",
     "country": "DE", "jurisdiction": "DE", "region": "EU", "source_class": "industrial_ministry",
     "domain": "industrial_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bmwk.de", "canonical_url": "https://www.bmwk.de",
     "acquisition_endpoint": "https://www.bmwk.de/Redaktion/EN/Rss/bmwk-rss.xml",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["energy", "manufacturing", "technology"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-cma-energy", "institution_id": "CMA", "institution_name": "Competition and Markets Authority (UK)",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "competition_authority",
     "domain": "competition_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "gov.uk", "canonical_url": "https://www.gov.uk/government/organisations/competition-and-markets-authority",
     "acquisition_endpoint": "https://www.gov.uk/government/organisations/competition-and-markets-authority.atom",
     "endpoint_type": "ATOM", "acquisition_method": "ATOM", "language": "en",
     "coverage_topics": ["competition"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-mcie-china", "institution_id": "MIIT", "institution_name": "Ministry of Industry and Information Technology (China)",
     "country": "CN", "jurisdiction": "CN", "region": "CN", "source_class": "industrial_ministry",
     "domain": "industrial_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "miit.gov.cn", "canonical_url": "https://www.miit.gov.cn",
     "acquisition_endpoint": "https://www.miit.gov.cn", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "zh",
     "coverage_topics": ["manufacturing", "technology"],
     "frequency": "weekly", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # LABOR & EMPLOYMENT (4)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-dol-us", "institution_id": "DOL", "institution_name": "US Department of Labor",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "labor_ministry",
     "domain": "labor_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "dol.gov", "canonical_url": "https://www.dol.gov",
     "acquisition_endpoint": "https://www.dol.gov/rss/pressreleases.htm",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["employment"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-eurostat-emp", "institution_id": "ESTATEMP", "institution_name": "Eurostat Employment",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "statistical_agency",
     "domain": "labor_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ec.europa.eu", "canonical_url": "https://ec.europa.eu/eurostat",
     "acquisition_endpoint": "https://ec.europa.eu/eurostat/web/main/news",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["employment"],
     "frequency": "monthly", "discovery_wave": "A"},

    {"source_id": "src-stat-korea", "institution_id": "KOSTAT", "institution_name": "Statistics Korea",
     "country": "KR", "jurisdiction": "KR", "region": "KR", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "kostat.go.kr", "canonical_url": "https://kostat.go.kr",
     "acquisition_endpoint": "https://kostat.go.kr", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "monthly", "discovery_wave": "A"},

    {"source_id": "src-mospi-india", "institution_id": "MOSPI", "institution_name": "Ministry of Statistics (India)",
     "country": "IN", "jurisdiction": "IN", "region": "IN", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "mospi.gov.in", "canonical_url": "https://www.mospi.gov.in",
     "acquisition_endpoint": "https://www.mospi.gov.in", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["gdp", "inflation", "employment"],
     "frequency": "monthly", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # BANKING REGULATORS (4)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-occ", "institution_id": "OCC", "institution_name": "Office of the Comptroller of the Currency",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "banking_regulator",
     "domain": "banking_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "occ.treas.gov", "canonical_url": "https://www.occ.treas.gov",
     "acquisition_endpoint": "https://www.occ.treas.gov/news-issuances/news-releases/index.html",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-fdic", "institution_id": "FDIC", "institution_name": "FDIC",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "banking_regulator",
     "domain": "banking_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fdic.gov", "canonical_url": "https://www.fdic.gov",
     "acquisition_endpoint": "https://www.fdic.gov/news/press-releases.html",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-ecb-banking", "institution_id": "ECBSM", "institution_name": "ECB Banking Supervision",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "banking_regulator",
     "domain": "banking_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "banking.supervision.europa.eu", "canonical_url": "https://www.banking.supervision.europa.eu",
     "acquisition_endpoint": "https://www.banking.supervision.europa.eu/press/rss/html/index.en.html",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-pboc-banking", "institution_id": "CBIRC", "institution_name": "China Banking and Insurance Regulatory Commission",
     "country": "CN", "jurisdiction": "CN", "region": "CN", "source_class": "banking_regulator",
     "domain": "banking_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "nfra.gov.cn", "canonical_url": "https://www.nfra.gov.cn",
     "acquisition_endpoint": "https://www.nfra.gov.cn", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "zh",
     "coverage_topics": ["banking", "insurance"],
     "frequency": "weekly", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # TRADE & CUSTOMS (4)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-ustr", "institution_id": "USTR", "institution_name": "Office of the US Trade Representative",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "trade_ministry",
     "domain": "trade_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "ustr.gov", "canonical_url": "https://ustr.gov",
     "acquisition_endpoint": "https://ustr.gov/about-us/policy-offices/press-office/press-releases",
     "endpoint_type": "HTML", "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["trade"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-cbp", "institution_id": "CBP", "institution_name": "US Customs and Border Protection",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "customs_authority",
     "domain": "trade_statistics", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbp.gov", "canonical_url": "https://www.cbp.gov",
     "acquisition_endpoint": "https://www.cbp.gov/news", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["trade", "external_sector"],
     "frequency": "daily", "discovery_wave": "A"},

    {"source_id": "src-dgtrade", "institution_id": "DGTR", "institution_name": "DG Trade (European Commission)",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "trade_ministry",
     "domain": "trade_policy", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "policy.trade.ec.europa.eu", "canonical_url": "https://policy.trade.ec.europa.eu",
     "acquisition_endpoint": "https://policy.trade.ec.europa.eu/news_en/rss.xml",
     "endpoint_type": "RSS", "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["trade"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-mitijapan", "institution_id": "METI", "institution_name": "Ministry of Economy, Trade and Industry (Japan)",
     "country": "JP", "jurisdiction": "JP", "region": "JP", "source_class": "trade_ministry",
     "domain": "trade_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "meti.go.jp", "canonical_url": "https://www.meti.go.jp",
     "acquisition_endpoint": "https://www.meti.go.jp/english/", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["trade", "manufacturing", "energy"],
     "frequency": "weekly", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # EMERGING MARKETS CENTRAL BANKS (8)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-rbi-india", "institution_id": "RBI", "institution_name": "Reserve Bank of India",
     "country": "IN", "jurisdiction": "IN", "region": "IN", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "rbi.org.in", "canonical_url": "https://www.rbi.org.in",
     "acquisition_endpoint": "https://www.rbi.org.in/Scripts/Rss.aspx", "endpoint_type": "RSS",
     "acquisition_method": "RSS", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-bank-korea", "institution_id": "BOK", "institution_name": "Bank of Korea",
     "country": "KR", "jurisdiction": "KR", "region": "KR", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bok.or.kr", "canonical_url": "https://www.bok.or.kr",
     "acquisition_endpoint": "https://www.bok.or.kr/eng/main.do", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-bank-mexico", "institution_id": "BANXICO", "institution_name": "Banco de México",
     "country": "MX", "jurisdiction": "MX", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "banxico.org.mx", "canonical_url": "https://www.banxico.org.mx",
     "acquisition_endpoint": "https://www.banxico.org.mx", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "es",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-bcb-brazil", "institution_id": "BCBB", "institution_name": "Banco Central do Brasil",
     "country": "BR", "jurisdiction": "BR", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bcb.gov.br", "canonical_url": "https://www.bcb.gov.br",
     "acquisition_endpoint": "https://www.bcb.gov.br", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "pt",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-sarb", "institution_id": "SARB", "institution_name": "South African Reserve Bank",
     "country": "ZA", "jurisdiction": "ZA", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "resbank.co.za", "canonical_url": "https://www.resbank.co.za",
     "acquisition_endpoint": "https://www.resbank.co.za/en/home/online-publications", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    {"source_id": "src-cbu-india", "institution_id": "CBU", "institution_name": "Central Bank of the UAE",
     "country": "AE", "jurisdiction": "AE", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "centralbank.ae", "canonical_url": "https://www.centralbank.ae",
     "acquisition_endpoint": "https://www.centralbank.ae/en/media-center/", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-sama-saudi", "institution_id": "SAMA", "institution_name": "Saudi Central Bank (SAMA)",
     "country": "SA", "jurisdiction": "SA", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "sama.gov.sa", "canonical_url": "https://www.sama.gov.sa",
     "acquisition_endpoint": "https://www.sama.gov.sa/en-US/Pages/default.aspx", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "banking"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-cb-turkey", "institution_id": "CBT", "institution_name": "Central Bank of the Republic of Turkey",
     "country": "TR", "jurisdiction": "TR", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "tcmb.gov.tr", "canonical_url": "https://www.tcmb.gov.tr",
     "acquisition_endpoint": "https://www.tcmb.gov.tr/wps/wcm/connect/EN/TCMB+EN", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["monetary_policy", "interest_rates"],
     "frequency": "event_driven", "discovery_wave": "A"},

    # ════════════════════════════════════════════════════════
    # SOVEREIGN WEALTH & PENSION (2)
    # ════════════════════════════════════════════════════════
    {"source_id": "src-nbim-norway", "institution_id": "NBIM", "institution_name": "Norges Bank Investment Management",
     "country": "NO", "jurisdiction": "NO", "region": "NORDICS", "source_class": "sovereign_wealth_institution",
     "domain": "sovereign_wealth", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nbim.no", "canonical_url": "https://www.nbim.no",
     "acquisition_endpoint": "https://www.nbim.no/en/news/", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["capital_markets"],
     "frequency": "weekly", "discovery_wave": "A"},

    {"source_id": "src-sspi-japan", "institution_id": "GPIF", "institution_name": "Government Pension Investment Fund (Japan)",
     "country": "JP", "jurisdiction": "JP", "region": "JP", "source_class": "pension_regulator",
     "domain": "pension_fund", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "gpif.go.jp", "canonical_url": "https://www.gpif.go.jp",
     "acquisition_endpoint": "https://www.gpif.go.jp/en/", "endpoint_type": "HTML",
     "acquisition_method": "HTML", "language": "en",
     "coverage_topics": ["pensions", "capital_markets"],
     "frequency": "monthly", "discovery_wave": "A"},
]


def get_catalog():
    """Return the discovery catalog."""
    return DISCOVERY_CATALOG


def catalog_stats():
    """Return summary stats of the catalog."""
    from collections import Counter
    by_country = Counter(s["country"] for s in DISCOVERY_CATALOG)
    by_region = Counter(s["region"] for s in DISCOVERY_CATALOG)
    by_class = Counter(s["source_class"] for s in DISCOVERY_CATALOG)
    by_authority = Counter(s["authority_level"] for s in DISCOVERY_CATALOG)
    by_method = Counter(s["acquisition_method"] for s in DISCOVERY_CATALOG)
    by_language = Counter(s["language"] for s in DISCOVERY_CATALOG)
    return {
        "total": len(DISCOVERY_CATALOG),
        "by_country": dict(by_country),
        "by_region": dict(by_region),
        "by_class": dict(by_class),
        "by_authority": dict(by_authority),
        "by_method": dict(by_method),
        "by_language": dict(by_language),
    }


if __name__ == "__main__":
    import json
    stats = catalog_stats()
    print(f"Discovery catalog: {stats['total']} sources")
    print(f"\nBy country:")
    for k, v in sorted(stats["by_country"].items(), key=lambda x: -x[1]):
        print(f"  {k:<10} {v:>3}")
    print(f"\nBy class:")
    for k, v in sorted(stats["by_class"].items(), key=lambda x: -x[1]):
        print(f"  {k:<35} {v:>3}")
    print(f"\nBy authority:")
    for k, v in sorted(stats["by_authority"].items(), key=lambda x: -x[1]):
        print(f"  {k:<25} {v:>3}")
    print(f"\nBy acquisition method:")
    for k, v in sorted(stats["by_method"].items(), key=lambda x: -x[1]):
        print(f"  {k:<10} {v:>3}")
