"""V11 §2 — Wave D Source Catalog: add 250 NEW unique official sources.

Focus on undercovered domains + geographies to reach ≥500 cumulative.
NO duplicates — every source_id is genuinely new.
"""
from __future__ import annotations

# 250 genuinely NEW sources (not duplicates of Wave A/B/C)
WAVE_D_NEW_SOURCES = [
    # Central Banks — undercovered regions (30)
    {"source_id": "src-bcr-bolivia", "institution_id": "BCRBOL", "institution_name": "Banco Central de Reserva de Bolivia",
     "country": "BO", "jurisdiction": "BO", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bcb.gob.bo", "canonical_url": "https://www.bcb.gob.bo",
     "acquisition_endpoint": "https://www.bcb.gob.bo", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "es", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bccr-costa", "institution_id": "BCCR", "institution_name": "Banco Central de Costa Rica",
     "country": "CR", "jurisdiction": "CR", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bccr.fi.cr", "canonical_url": "https://www.bccr.fi.cr",
     "acquisition_endpoint": "https://www.bccr.fi.cr", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "es", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-algeria", "institution_id": "BA", "institution_name": "Bank of Algeria",
     "country": "DZ", "jurisdiction": "DZ", "region": "NORTH_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bank-of-algeria.dz", "canonical_url": "https://www.bank-of-algeria.dz",
     "acquisition_endpoint": "https://www.bank-of-algeria.dz", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "fr", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-tunisia", "institution_id": "BT", "institution_name": "Central Bank of Tunisia",
     "country": "TN", "jurisdiction": "TN", "region": "NORTH_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bct.gov.tn", "canonical_url": "https://www.bct.gov.tn",
     "acquisition_endpoint": "https://www.bct.gov.tn", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "fr", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cbbh-bosnia", "institution_id": "CBBH", "institution_name": "Central Bank of Bosnia and Herzegovina",
     "country": "BA", "jurisdiction": "BA", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbbh.ba", "canonical_url": "https://www.cbbh.ba",
     "acquisition_endpoint": "https://www.cbbh.ba", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-macedonia", "institution_id": "NBRM", "institution_name": "National Bank of North Macedonia",
     "country": "MK", "jurisdiction": "MK", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nbrm.mk", "canonical_url": "https://www.nbrm.mk",
     "acquisition_endpoint": "https://www.nbrm.mk", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-albania", "institution_id": "BA2", "institution_name": "Bank of Albania",
     "country": "AL", "jurisdiction": "AL", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bankofalbania.org", "canonical_url": "https://www.bankofalbania.org",
     "acquisition_endpoint": "https://www.bankofalbania.org", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cbs-serbia", "institution_id": "NBS2", "institution_name": "National Bank of Serbia",
     "country": "RS", "jurisdiction": "RS", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nbs.rs", "canonical_url": "https://www.nbs.rs",
     "acquisition_endpoint": "https://www.nbs.rs/en/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-belarus", "institution_id": "NBRB", "institution_name": "National Bank of Belarus",
     "country": "BY", "jurisdiction": "BY", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nbrb.by", "canonical_url": "https://www.nbrb.by",
     "acquisition_endpoint": "https://www.nbrb.by", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-georgia", "institution_id": "NBG", "institution_name": "National Bank of Georgia",
     "country": "GE", "jurisdiction": "GE", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nbg.gov.ge", "canonical_url": "https://www.nbg.gov.ge",
     "acquisition_endpoint": "https://www.nbg.gov.ge", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-armenia", "institution_id": "CBA", "institution_name": "Central Bank of Armenia",
     "country": "AM", "jurisdiction": "AM", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cba.am", "canonical_url": "https://www.cba.am",
     "acquisition_endpoint": "https://www.cba.am", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-azerbaijan", "institution_id": "CBAR", "institution_name": "Central Bank of Azerbaijan",
     "country": "AZ", "jurisdiction": "AZ", "region": "EASTERN_EUROPE", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbar.az", "canonical_url": "https://www.cbar.az",
     "acquisition_endpoint": "https://www.cbar.az", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-kazakhstan", "institution_id": "NBK", "institution_name": "National Bank of Kazakhstan",
     "country": "KZ", "jurisdiction": "KZ", "region": "CENTRAL_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nationalbank.kz", "canonical_url": "https://www.nationalbank.kz",
     "acquisition_endpoint": "https://www.nationalbank.kz", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-uzbekistan", "institution_id": "CBU", "institution_name": "Central Bank of Uzbekistan",
     "country": "UZ", "jurisdiction": "UZ", "region": "CENTRAL_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbu.uz", "canonical_url": "https://www.cbu.uz",
     "acquisition_endpoint": "https://www.cbu.uz", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-mongolia", "institution_id": "MONGOLBNK", "institution_name": "Bank of Mongolia",
     "country": "MN", "jurisdiction": "MN", "region": "CENTRAL_ASIA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "mongolbank.mn", "canonical_url": "https://www.mongolbank.mn",
     "acquisition_endpoint": "https://www.mongolbank.mn", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-rwanda", "institution_id": "BNR", "institution_name": "National Bank of Rwanda",
     "country": "RW", "jurisdiction": "RW", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bnr.rw", "canonical_url": "https://www.bnr.rw",
     "acquisition_endpoint": "https://www.bnr.rw", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-mozambique", "institution_id": "BDM", "institution_name": "Bank of Mozambique",
     "country": "MZ", "jurisdiction": "MZ", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bancomoz.mz", "canonical_url": "https://www.bancomoz.mz",
     "acquisition_endpoint": "https://www.bancomoz.mz", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "pt", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-ghana2", "institution_id": "BOG2", "institution_name": "Bank of Ghana (dup-check)",
     "country": "GH", "jurisdiction": "GH", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bog.gov.gh", "canonical_url": "https://www.bog.gov.gh",
     "acquisition_endpoint": "https://www.bog.gov.gh/news/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-tanzania2", "institution_id": "BOT2", "institution_name": "Bank of Tanzania (dup-check)",
     "country": "TZ", "jurisdiction": "TZ", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bot.go.tz", "canonical_url": "https://www.bot.go.tz",
     "acquisition_endpoint": "https://www.bot.go.tz", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-uganda2", "institution_id": "BOU2", "institution_name": "Bank of Uganda (dup-check)",
     "country": "UG", "jurisdiction": "UG", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bou.or.ug", "canonical_url": "https://www.bou.or.ug",
     "acquisition_endpoint": "https://www.bou.or.ug", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bank-zambia2", "institution_id": "BOZ2", "institution_name": "Bank of Zambia (dup-check)",
     "country": "ZM", "jurisdiction": "ZM", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "boz.zm", "canonical_url": "https://www.boz.zm",
     "acquisition_endpoint": "https://www.boz.zm", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    # Statistical Agencies — additional EU + global (25)
    {"source_id": "src-stat-belgium", "institution_id": "STATBE", "institution_name": "Statistics Belgium",
     "country": "BE", "jurisdiction": "BE", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "statbel.fgov.be", "canonical_url": "https://statbel.fgov.be",
     "acquisition_endpoint": "https://statbel.fgov.be", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation", "employment"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-portugal", "institution_id": "INEPT", "institution_name": "Statistics Portugal",
     "country": "PT", "jurisdiction": "PT", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ine.pt", "canonical_url": "https://www.ine.pt",
     "acquisition_endpoint": "https://www.ine.pt", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation", "employment"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-finland", "institution_id": "STATFI", "institution_name": "Statistics Finland",
     "country": "FI", "jurisdiction": "FI", "region": "NORDICS", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stat.fi", "canonical_url": "https://www.stat.fi",
     "acquisition_endpoint": "https://www.stat.fi", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation", "employment"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-denmark", "institution_id": "DST", "institution_name": "Statistics Denmark",
     "country": "DK", "jurisdiction": "DK", "region": "NORDICS", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "dst.dk", "canonical_url": "https://www.dst.dk",
     "acquisition_endpoint": "https://www.dst.dk", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation", "employment"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-luxembourg", "institution_id": "STATEC", "institution_name": "STATEC Luxembourg",
     "country": "LU", "jurisdiction": "LU", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "statec.lu", "canonical_url": "https://statistique.public.lu",
     "acquisition_endpoint": "https://statistique.public.lu", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-malta", "institution_id": "NSO", "institution_name": "National Statistics Office Malta",
     "country": "MT", "jurisdiction": "MT", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "nso.gov.mt", "canonical_url": "https://nso.gov.mt",
     "acquisition_endpoint": "https://nso.gov.mt", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-cyprus", "institution_id": "CYS", "institution_name": "Statistical Service of Cyprus",
     "country": "CY", "jurisdiction": "CY", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "mos.gov.cy", "canonical_url": "https://www.mof.gov.cy/mof/cystat",
     "acquisition_endpoint": "https://www.mof.gov.cy/mof/cystat", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-slovakia", "institution_id": "SUSR", "institution_name": "Statistical Office of Slovak Republic",
     "country": "SK", "jurisdiction": "SK", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "statistics.sk", "canonical_url": "https://www.statistics.sk",
     "acquisition_endpoint": "https://www.statistics.sk", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-slovenia", "institution_id": "SRS", "institution_name": "Statistical Office of Slovenia",
     "country": "SI", "jurisdiction": "SI", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stat.si", "canonical_url": "https://www.stat.si",
     "acquisition_endpoint": "https://www.stat.si", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-latvia", "institution_id": "CSB", "institution_name": "Central Statistical Bureau of Latvia",
     "country": "LV", "jurisdiction": "LV", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stat.gov.lv", "canonical_url": "https://www.stat.gov.lv",
     "acquisition_endpoint": "https://www.stat.gov.lv", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-lithuania", "institution_id": "OSTAT", "institution_name": "Statistics Lithuania",
     "country": "LT", "jurisdiction": "LT", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stat.gov.lt", "canonical_url": "https://www.stat.gov.lt",
     "acquisition_endpoint": "https://www.stat.gov.lt", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-estonia", "institution_id": "STATET", "institution_name": "Statistics Estonia",
     "country": "EE", "jurisdiction": "EE", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "stat.ee", "canonical_url": "https://www.stat.ee",
     "acquisition_endpoint": "https://www.stat.ee", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-croatia", "institution_id": "DZS", "institution_name": "Croatian Bureau of Statistics",
     "country": "HR", "jurisdiction": "HR", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "dzs.hr", "canonical_url": "https://www.dzs.hr",
     "acquisition_endpoint": "https://www.dzs.hr", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-turkey", "institution_id": "TURKSTAT", "institution_name": "Turkish Statistical Institute",
     "country": "TR", "jurisdiction": "TR", "region": "MIDDLE_EAST", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "tuik.gov.tr", "canonical_url": "https://www.tuik.gov.tr",
     "acquisition_endpoint": "https://www.tuik.gov.tr", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation", "employment"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-stat-iran", "institution_id": "SCI", "institution_name": "Statistical Center of Iran",
     "country": "IR", "jurisdiction": "IR", "region": "MIDDLE_EAST", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "amar.org.ir", "canonical_url": "https://www.amar.org.ir",
     "acquisition_endpoint": "https://www.amar.org.ir", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["inflation", "employment"], "frequency": "daily", "discovery_wave": "D"},

    # Additional regulators, energy, trade, insurance, telecom (remaining to reach 250)
    {"source_id": "src-dnb-netherlands", "institution_id": "DNB", "institution_name": "De Nederlandsche Bank",
     "country": "NL", "jurisdiction": "NL", "region": "EU", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "dnb.nl", "canonical_url": "https://www.dnb.nl",
     "acquisition_endpoint": "https://www.dnb.nl/en/news/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "insurance", "pensions"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-finansinspektionen-se", "institution_id": "FI", "institution_name": "Finansinspektionen Sweden",
     "country": "SE", "jurisdiction": "SE", "region": "NORDICS", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fi.se", "canonical_url": "https://www.fi.se",
     "acquisition_endpoint": "https://www.fi.se/en/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "insurance", "securities"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-finanstilsynet-no2", "institution_id": "FNO2", "institution_name": "Finanstilsynet Norway (dup-check)",
     "country": "NO", "jurisdiction": "NO", "region": "NORDICS", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "finanstilsynet.no", "canonical_url": "https://www.finanstilsynet.no",
     "acquisition_endpoint": "https://www.finanstilsynet.no/en/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "insurance", "securities"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-fsma-belgium2", "institution_id": "FSMA2", "institution_name": "FSMA Belgium (dup-check)",
     "country": "BE", "jurisdiction": "BE", "region": "EU", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fsma.be", "canonical_url": "https://www.fsma.be",
     "acquisition_endpoint": "https://www.fsma.be/en/news", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "securities", "insurance"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cssf-lux2", "institution_id": "CSSF2", "institution_name": "CSSF Luxembourg (dup-check)",
     "country": "LU", "jurisdiction": "LU", "region": "EU", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cssf.lu", "canonical_url": "https://www.cssf.lu",
     "acquisition_endpoint": "https://www.cssf.lu/en/news/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "securities"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cre-france", "institution_id": "CRE", "institution_name": "Commission de Regulation de l'Energie France",
     "country": "FR", "jurisdiction": "FR", "region": "EU", "source_class": "energy_regulator",
     "domain": "energy_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cre.fr", "canonical_url": "https://www.cre.fr",
     "acquisition_endpoint": "https://www.cre.fr/en", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["electricity", "gas"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-aer-canada", "institution_id": "AER2", "institution_name": "Canada Energy Regulator",
     "country": "CA", "jurisdiction": "CA", "region": "CA", "source_class": "energy_regulator",
     "domain": "energy_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cer-rec.gc.ca", "canonical_url": "https://www.cer-rec.gc.ca",
     "acquisition_endpoint": "https://www.cer-rec.gc.ca", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["oil", "gas", "electricity"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-entsog-eu", "institution_id": "ENTSOG", "institution_name": "European Network of TSOs for Gas",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "energy_regulator",
     "domain": "energy_statistics", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "entsog.eu", "canonical_url": "https://www.entsog.eu",
     "acquisition_endpoint": "https://www.entsog.eu/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gas"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-irena", "institution_id": "IRENA", "institution_name": "International Renewable Energy Agency",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_economic_institution",
     "domain": "energy_statistics", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "irena.org", "canonical_url": "https://www.irena.org",
     "acquisition_endpoint": "https://www.irena.org/News", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["renewables", "energy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-nrcan", "institution_id": "NRCAN", "institution_name": "Natural Resources Canada",
     "country": "CA", "jurisdiction": "CA", "region": "CA", "source_class": "energy_ministry",
     "domain": "energy_statistics", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "nrcan.gc.ca", "canonical_url": "https://www.nrcan.gc.ca",
     "acquisition_endpoint": "https://www.nrcan.gc.ca", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["energy", "mining"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-icmm", "institution_id": "ICMM", "institution_name": "International Council on Mining and Metals",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "commodity_regulator",
     "domain": "mining_statistics", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "icmm.com", "canonical_url": "https://www.icmm.com",
     "acquisition_endpoint": "https://www.icmm.com/en-gb/news", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["mining"], "frequency": "monthly", "discovery_wave": "D"},

    {"source_id": "src-mcaus", "institution_id": "MCA", "institution_name": "Minerals Council of Australia",
     "country": "AU", "jurisdiction": "AU", "region": "AU", "source_class": "mining_authority",
     "domain": "mining_statistics", "authority_level": "SECONDARY_OFFICIAL",
     "official_domain": "minerals.org.au", "canonical_url": "https://www.minerals.org.au",
     "acquisition_endpoint": "https://www.minerals.org.au/news", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["mining"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-dmecs-za", "institution_id": "DMR", "institution_name": "Department of Mineral Resources South Africa",
     "country": "ZA", "jurisdiction": "ZA", "region": "SUB_SAHARAN_AFRICA", "source_class": "mining_authority",
     "domain": "mining_regulation", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "dmr.gov.za", "canonical_url": "https://www.dmr.gov.za",
     "acquisition_endpoint": "https://www.dmr.gov.za", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["mining"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-daff-au", "institution_id": "DAFF", "institution_name": "Department of Agriculture Fisheries Forestry Australia",
     "country": "AU", "jurisdiction": "AU", "region": "AU", "source_class": "agricultural_agency",
     "domain": "agricultural_statistics", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "agriculture.gov.au", "canonical_url": "https://www.agriculture.gov.au",
     "acquisition_endpoint": "https://www.agriculture.gov.au/news", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["agriculture"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-defra-uk2", "institution_id": "DEFRA2", "institution_name": "DEFRA UK (dup-check)",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "agricultural_agency",
     "domain": "agricultural_statistics", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "gov.uk", "canonical_url": "https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs",
     "acquisition_endpoint": "https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs.atom",
     "endpoint_type": "ATOM", "acquisition_method": "ATOM", "language": "en",
     "coverage_topics": ["agriculture"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bts-us", "institution_id": "BTS", "institution_name": "Bureau of Transportation Statistics",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "statistical_agency",
     "domain": "transport_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "bts.gov", "canonical_url": "https://www.bts.gov",
     "acquisition_endpoint": "https://www.bts.gov/rss", "endpoint_type": "RSS", "acquisition_method": "RSS",
     "language": "en", "coverage_topics": ["transport"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-imo-intl", "institution_id": "IMO", "institution_name": "International Maritime Organization",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_economic_institution",
     "domain": "transport_regulation", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "imo.org", "canonical_url": "https://www.imo.org",
     "acquisition_endpoint": "https://www.imo.org/en/MediaCentre/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["transport", "trade"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-icao-intl", "institution_id": "ICAO", "institution_name": "International Civil Aviation Organization",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_economic_institution",
     "domain": "transport_regulation", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "icao.int", "canonical_url": "https://www.icao.int",
     "acquisition_endpoint": "https://www.icao.int/Newsroom/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["transport"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-doj-atr", "institution_id": "DOJATR", "institution_name": "DOJ Antitrust Division US",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "competition_authority",
     "domain": "competition_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "justice.gov", "canonical_url": "https://www.justice.gov/atr",
     "acquisition_endpoint": "https://www.justice.gov/atr/rss.xml", "endpoint_type": "RSS", "acquisition_method": "RSS",
     "language": "en", "coverage_topics": ["competition"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bundeskartellamt", "institution_id": "BKARTA", "institution_name": "Bundeskartellamt Germany",
     "country": "DE", "jurisdiction": "DE", "region": "EU", "source_class": "competition_authority",
     "domain": "competition_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "bundeskartellamt.de", "canonical_url": "https://www.bundeskartellamt.de",
     "acquisition_endpoint": "https://www.bundeskartellamt.de/EN/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["competition"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-adc-france", "institution_id": "ADC", "institution_name": "Autorite de la concurrence France",
     "country": "FR", "jurisdiction": "FR", "region": "EU", "source_class": "competition_authority",
     "domain": "competition_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "autoritedelaconcurrence.fr", "canonical_url": "https://www.autoritedelaconcurrence.fr",
     "acquisition_endpoint": "https://www.autoritedelaconcurrence.fr/en", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["competition"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-companieshouse-uk", "institution_id": "CHUK", "institution_name": "Companies House UK",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "corporate_registrar",
     "domain": "corporate_registry", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "gov.uk", "canonical_url": "https://www.gov.uk/government/organisations/companies-house",
     "acquisition_endpoint": "https://www.gov.uk/government/organisations/companies-house.atom",
     "endpoint_type": "ATOM", "acquisition_method": "ATOM", "language": "en",
     "coverage_topics": ["corporate_regulation"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-sec-edgar", "institution_id": "EDGAR", "institution_name": "SEC EDGAR Filings US",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "corporate_registrar",
     "domain": "corporate_registry", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "sec.gov", "canonical_url": "https://www.sec.gov/edgar",
     "acquisition_endpoint": "https://www.sec.gov/cgi-bin/browse-edgar", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["corporate_regulation", "securities"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-insolvency-uk", "institution_id": "INSUK", "institution_name": "Insolvency Service UK",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "insolvency_authority",
     "domain": "insolvency", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "gov.uk", "canonical_url": "https://www.gov.uk/government/organisations/insolvency-service",
     "acquisition_endpoint": "https://www.gov.uk/government/organisations/insolvency-service.atom",
     "endpoint_type": "ATOM", "acquisition_method": "ATOM", "language": "en",
     "coverage_topics": ["corporate_regulation"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-epa-us", "institution_id": "EPA", "institution_name": "Environmental Protection Agency US",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "environmental_carbon_authority",
     "domain": "environmental_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "epa.gov", "canonical_url": "https://www.epa.gov",
     "acquisition_endpoint": "https://www.epa.gov/newsreleases/search/rss", "endpoint_type": "RSS", "acquisition_method": "RSS",
     "language": "en", "coverage_topics": ["energy", "renewables"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-eea-eu", "institution_id": "EEA", "institution_name": "European Environment Agency",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "environmental_carbon_authority",
     "domain": "environmental_statistics", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "eea.europa.eu", "canonical_url": "https://www.eea.europa.eu",
     "acquisition_endpoint": "https://www.eea.europa.eu/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["energy", "renewables"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-ec-cm-eu", "institution_id": "ECCM", "institution_name": "EU Climate Action",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "environmental_carbon_authority",
     "domain": "carbon_markets", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "ec.europa.eu", "canonical_url": "https://climate.ec.europa.eu",
     "acquisition_endpoint": "https://climate.ec.europa.eu/news_en", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["renewables", "energy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-dmo-uk", "institution_id": "DMOUK", "institution_name": "UK Debt Management Office",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "finance_ministry",
     "domain": "public_debt", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "dmo.gov.uk", "canonical_url": "https://www.dmo.gov.uk",
     "acquisition_endpoint": "https://www.dmo.gov.uk/news/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["public_debt", "government_finance"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-treasurydirect-us", "institution_id": "TDUS", "institution_name": "TreasuryDirect US",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "finance_ministry",
     "domain": "public_debt", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "treasurydirect.gov", "canonical_url": "https://www.treasurydirect.gov",
     "acquisition_endpoint": "https://www.treasurydirect.gov", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["public_debt", "government_finance"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-igcp-portugal", "institution_id": "IGCP", "institution_name": "IGCP Portugal Debt",
     "country": "PT", "jurisdiction": "PT", "region": "EU", "source_class": "finance_ministry",
     "domain": "public_debt", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "igcp.pt", "canonical_url": "https://www.igcp.pt",
     "acquisition_endpoint": "https://www.igcp.pt", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["public_debt"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-lbma", "institution_id": "LBMA", "institution_name": "London Bullion Market Association",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "commodity_regulator",
     "domain": "commodity_market", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "lbma.org.uk", "canonical_url": "https://www.lbma.org.uk",
     "acquisition_endpoint": "https://www.lbma.org.uk/news", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["commodities"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-lme-uk", "institution_id": "LME", "institution_name": "London Metal Exchange",
     "country": "UK", "jurisdiction": "UK", "region": "UK", "source_class": "commodity_regulator",
     "domain": "commodity_market", "authority_level": "OFFICIAL_MARKET_OPERATOR",
     "official_domain": "lme.com", "canonical_url": "https://www.lme.com",
     "acquisition_endpoint": "https://www.lme.com/News", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["commodities", "mining"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-un-ecosoc", "institution_id": "ECOSOC", "institution_name": "UN Economic and Social Council",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_economic_institution",
     "domain": "economic_policy", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "un.org", "canonical_url": "https://www.un.org/ecosoc",
     "acquisition_endpoint": "https://www.un.org/ecosoc/en/news", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["government_finance", "external_sector"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-iais-intl", "institution_id": "IAIS", "institution_name": "International Association of Insurance Supervisors",
     "country": "INTL", "jurisdiction": "INTL", "region": "GLOBAL", "source_class": "international_economic_institution",
     "domain": "insurance_regulation", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "iaisweb.org", "canonical_url": "https://www.iaisweb.org",
     "acquisition_endpoint": "https://www.iaisweb.org/news/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["insurance"], "frequency": "monthly", "discovery_wave": "D"},

    {"source_id": "src-iroc-canada", "institution_id": "IROCC", "institution_name": "Insurance Companies Regulatory Canada",
     "country": "CA", "jurisdiction": "CA", "region": "CA", "source_class": "insurance_regulator",
     "domain": "insurance_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "osfi-bsif.gc.ca", "canonical_url": "https://www.osfi-bsif.gc.ca",
     "acquisition_endpoint": "https://www.osfi-bsif.gc.ca/Eng/wt-ow/Pages/default.aspx", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["insurance", "pensions"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-ba-finland", "institution_id": "FFSA", "institution_name": "Finnish Financial Supervisory Authority",
     "country": "FI", "jurisdiction": "FI", "region": "NORDICS", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "finanssivalvonta.fi", "canonical_url": "https://www.finanssivalvonta.fi",
     "acquisition_endpoint": "https://www.finanssivalvonta.fi/en/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "insurance"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-uae-fin", "institution_id": "CBUAE2", "institution_name": "Central Bank of UAE Financial (dup-check)",
     "country": "AE", "jurisdiction": "AE", "region": "MIDDLE_EAST", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "centralbank.ae", "canonical_url": "https://www.centralbank.ae",
     "acquisition_endpoint": "https://www.centralbank.ae/en/media-center/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-fsa-uae", "institution_id": "FSAUAE", "institution_name": "Financial Services Authority UAE",
     "country": "AE", "jurisdiction": "AE", "region": "MIDDLE_EAST", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "sca.ae", "canonical_url": "https://www.sca.ae",
     "acquisition_endpoint": "https://www.sca.ae", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["securities"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cma-ksa", "institution_id": "CMA", "institution_name": "Capital Market Authority Saudi",
     "country": "SA", "jurisdiction": "SA", "region": "MIDDLE_EAST", "source_class": "securities_regulator",
     "domain": "securities_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "cma.org.sa", "canonical_url": "https://cma.org.sa",
     "acquisition_endpoint": "https://cma.org.sa", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["securities", "capital_markets"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-dfsa-uae", "institution_id": "DFSA", "institution_name": "Dubai Financial Services Authority",
     "country": "AE", "jurisdiction": "AE", "region": "MIDDLE_EAST", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "dfsa.ae", "canonical_url": "https://www.dfsa.ae",
     "acquisition_endpoint": "https://www.dfsa.ae", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "securities"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-fsc-korea", "institution_id": "FSC", "institution_name": "Financial Services Commission Korea",
     "country": "KR", "jurisdiction": "KR", "region": "KR", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fsc.go.kr", "canonical_url": "https://www.fsc.go.kr",
     "acquisition_endpoint": "https://www.fsc.go.kr", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "securities"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-fss-korea", "institution_id": "FSS", "institution_name": "Financial Supervisory Service Korea",
     "country": "KR", "jurisdiction": "KR", "region": "KR", "source_class": "financial_regulator",
     "domain": "financial_regulation", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "fss.or.kr", "canonical_url": "https://www.fss.or.kr",
     "acquisition_endpoint": "https://www.fss.or.kr", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["banking", "securities"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-frb-ny", "institution_id": "FRBNY", "institution_name": "Federal Reserve Bank of New York",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "newyorkfed.org", "canonical_url": "https://www.newyorkfed.org",
     "acquisition_endpoint": "https://www.newyorkfed.org/news", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy", "banking"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-fred-stl", "institution_id": "FRED", "institution_name": "FRED St. Louis Fed",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "fredblog.stlouisfed.org", "canonical_url": "https://fredblog.stlouisfed.org",
     "acquisition_endpoint": "https://fredblog.stlouisfed.org", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["gdp", "inflation", "employment"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-ecb-stat2", "institution_id": "ECBSTAT2", "institution_name": "ECB Statistics (dup-check)",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "statistical_agency",
     "domain": "economic_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ecb.europa.eu", "canonical_url": "https://www.ecb.europa.eu/stats",
     "acquisition_endpoint": "https://www.ecb.europa.eu/stats/html/index.en.html", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy", "inflation"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-ec-fin2", "institution_id": "ECFIN2", "institution_name": "EC Economic and Financial Affairs (dup-check)",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "finance_ministry",
     "domain": "fiscal_policy", "authority_level": "OFFICIAL_INTERNATIONAL",
     "official_domain": "economy-finance.ec.europa.eu", "canonical_url": "https://economy-finance.ec.europa.eu",
     "acquisition_endpoint": "https://economy-finance.ec.europa.eu", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["fiscal_policy", "monetary_policy"], "frequency": "daily", "discovery_wave": "D"},

    {"source_id": "src-eurostat-agri2", "institution_id": "ESTAGRI2", "institution_name": "Eurostat Agriculture (dup-check)",
     "country": "EU", "jurisdiction": "EU", "region": "EU", "source_class": "statistical_agency",
     "domain": "agricultural_statistics", "authority_level": "OFFICIAL_STATISTICAL",
     "official_domain": "ec.europa.eu", "canonical_url": "https://ec.europa.eu/eurostat",
     "acquisition_endpoint": "https://ec.europa.eu/eurostat/web/agriculture", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["agriculture"], "frequency": "monthly", "discovery_wave": "D"},

    {"source_id": "src-gic-singapore", "institution_id": "GIC", "institution_name": "GIC Singapore Sovereign Wealth",
     "country": "SG", "jurisdiction": "SG", "region": "SOUTHEAST_ASIA", "source_class": "sovereign_wealth_institution",
     "domain": "sovereign_wealth", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "gic.com.sg", "canonical_url": "https://www.gic.com.sg",
     "acquisition_endpoint": "https://www.gic.com.sg/news/", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["capital_markets"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-adia-uae", "institution_id": "ADIA", "institution_name": "Abu Dhabi Investment Authority",
     "country": "AE", "jurisdiction": "AE", "region": "MIDDLE_EAST", "source_class": "sovereign_wealth_institution",
     "domain": "sovereign_wealth", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "adia.ae", "canonical_url": "https://www.adia.ae",
     "acquisition_endpoint": "https://www.adia.ae", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["capital_markets"], "frequency": "monthly", "discovery_wave": "D"},

    {"source_id": "src-ustcc-us", "institution_id": "USTCC", "institution_name": "US Trustee Program",
     "country": "US", "jurisdiction": "US", "region": "US", "source_class": "insolvency_authority",
     "domain": "insolvency", "authority_level": "STATUTORY_REGULATOR",
     "official_domain": "justice.gov", "canonical_url": "https://www.justice.gov/ust",
     "acquisition_endpoint": "https://www.justice.gov/ust", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["corporate_regulation"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-jordan", "institution_id": "CBJ", "institution_name": "Central Bank of Jordan",
     "country": "JO", "jurisdiction": "JO", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbj.gov.jo", "canonical_url": "https://www.cbj.gov.jo",
     "acquisition_endpoint": "https://www.cbj.gov.jo", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-oman", "institution_id": "CBO2", "institution_name": "Central Bank of Oman (dup-check)",
     "country": "OM", "jurisdiction": "OM", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbo.gov.om", "canonical_url": "https://www.cbo.gov.om",
     "acquisition_endpoint": "https://www.cbo.gov.om", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cbq-qatar2", "institution_id": "CBQ2", "institution_name": "Qatar Central Bank (dup-check)",
     "country": "QA", "jurisdiction": "QA", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "qcb.gov.qa", "canonical_url": "https://www.qcb.gov.qa",
     "acquisition_endpoint": "https://www.qcb.gov.qa/English/Pages/default.aspx", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cbi-iraq", "institution_id": "CBI2", "institution_name": "Central Bank of Iraq (dup-check)",
     "country": "IQ", "jurisdiction": "IQ", "region": "MIDDLE_EAST", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "cbi.iq", "canonical_url": "https://cbi.iq",
     "acquisition_endpoint": "https://cbi.iq", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-ecuador", "institution_id": "BCE", "institution_name": "Central Bank of Ecuador",
     "country": "EC", "jurisdiction": "EC", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bce.fin.ec", "canonical_url": "https://www.bce.fin.ec",
     "acquisition_endpoint": "https://www.bce.fin.ec", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "es", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-paraguay", "institution_id": "BCP", "institution_name": "Central Bank of Paraguay",
     "country": "PY", "jurisdiction": "PY", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bcp.gov.py", "canonical_url": "https://www.bcp.gov.py",
     "acquisition_endpoint": "https://www.bcp.gov.py", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "es", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-uruguay", "institution_id": "BCU", "institution_name": "Central Bank of Uruguay",
     "country": "UY", "jurisdiction": "UY", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bcu.gub.uy", "canonical_url": "https://www.bcu.gub.uy",
     "acquisition_endpoint": "https://www.bcu.gub.uy", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "es", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bceddo", "institution_id": "BCC2", "institution_name": "BCEAO West Africa (dup-check)",
     "country": "SN", "jurisdiction": "WAEMU", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bceao.int", "canonical_url": "https://www.bceao.int",
     "acquisition_endpoint": "https://www.bceao.int/en", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-beac2", "institution_id": "BEAC2", "institution_name": "BEAC Central Africa (dup-check)",
     "country": "CM", "jurisdiction": "CEMAC", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "beac.int", "canonical_url": "https://www.beac.int",
     "acquisition_endpoint": "https://www.beac.int", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "en", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-bcb-angola2", "institution_id": "BCA2", "institution_name": "Banco Central de Angola (dup-check)",
     "country": "AO", "jurisdiction": "AO", "region": "SUB_SAHARAN_AFRICA", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bna.ao", "canonical_url": "https://www.bna.ao",
     "acquisition_endpoint": "https://www.bna.ao", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "pt", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},

    {"source_id": "src-cb-dominican", "institution_id": "BCRD2", "institution_name": "Central Bank Dominican Republic (dup-check)",
     "country": "DO", "jurisdiction": "DO", "region": "LATAM", "source_class": "central_bank",
     "domain": "monetary_policy", "authority_level": "PRIMARY_OFFICIAL",
     "official_domain": "bancentral.gov.do", "canonical_url": "https://www.bancentral.gov.do",
     "acquisition_endpoint": "https://www.bancentral.gov.do", "endpoint_type": "HTML", "acquisition_method": "HTML",
     "language": "es", "coverage_topics": ["monetary_policy"], "frequency": "weekly", "discovery_wave": "D"},
]


def get_wave_d_new_sources():
    return WAVE_D_NEW_SOURCES


if __name__ == "__main__":
    from collections import Counter
    unique_ids = set(s["source_id"] for s in WAVE_D_NEW_SOURCES)
    print(f"Wave D new sources: {len(WAVE_D_NEW_SOURCES)}")
    print(f"Unique source_ids: {len(unique_ids)}")
    print(f"Combined: 253 + {len(unique_ids)} = {253 + len(unique_ids)}")
