"""V2-Real §2 — Audit the 111 IOs in corpus_100_store.

Classify every IO as:
  REAL_OFFICIAL_SOURCE — traced to a real HTTP retrieval event with a real URL
  SYNTHETIC_TEST       — generated by synthetic test fixtures (src-job-XXXX)
  CANONICAL_FIXTURE    — from canonical mock / seed fixtures
  UNKNOWN              — cannot determine

Trace path for each IO:
  io_id
    ↓ (event_id, event_version)
  event_row.document_id
    ↓
  document.source_id
    ↓
  source.source_path  (the real URL if REAL_OFFICIAL_SOURCE)
    ↓
  retrieval_event.requested_url  (the actual HTTP fetch)

A REAL_OFFICIAL_SOURCE IO must have:
  - source.source_path starting with http(s)://
  - document.canonical_url starting with http(s)://
  - at least one retrieval_event for the document
  - source_id NOT matching synthetic patterns (src-job-XXXX, INST-job-XXXX)
"""
from __future__ import annotations
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

CORE_REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(CORE_REPO))

from intelligence_core.cached_store import CachedStore
from intelligence_core.store import AppendOnlyStore
from intelligence_core.identity import io_id as make_io_id
from intelligence_core.delivery import build_intelligence_object


SYNTHETIC_PATTERNS = [
    re.compile(r"^src-job-\d+$"),
    re.compile(r"^INST-job-\d+$"),
    re.compile(r"^doc-job-\d+-"),
    re.compile(r"^rep-job-\d+-"),
    re.compile(r"^evt-job-\d+$"),
    re.compile(r"^fact-job-\d+-"),
    re.compile(r"^ret-job-\d+-"),
]

CANONICAL_PATTERNS = [
    re.compile(r"^io-cpi-v\d+$"),
    re.compile(r"^io-fdic-"),
    re.compile(r"^evt-cpi-"),
    re.compile(r"^doc-cpi-"),
    re.compile(r"^src-istat-"),
    re.compile(r"^src-fdic-"),
]


def classify_id(id_str: str) -> str:
    for pat in SYNTHETIC_PATTERNS:
        if pat.match(id_str):
            return "SYNTHETIC_TEST"
    for pat in CANONICAL_PATTERNS:
        if pat.match(id_str):
            return "CANONICAL_FIXTURE"
    return "UNKNOWN"


def audit_store(store_root: str):
    """Audit every IO in the store and classify it."""
    store = CachedStore(AppendOnlyStore(store_root))

    # Build lookup tables
    sources_by_id = store.latest_by_id("sources", "source_id")
    docs_by_id = store.latest_by_id("documents", "document_id")
    reps_by_id = store.latest_by_id("representations", "representation_id")
    retrieval_events = list(store.iter("retrieval_events"))
    retrieval_by_url = {r.get("requested_url", ""): r for r in retrieval_events}

    classifications = []
    real_count = 0
    synthetic_count = 0
    canonical_count = 0
    unknown_count = 0

    for ev in store.iter("events"):
        io_id_str = make_io_id(ev["event_id"], ev["event_version"])
        doc_id = ev.get("document_id", "")
        doc = docs_by_id.get(doc_id, {})
        source_id = doc.get("source_id", "")
        source = sources_by_id.get(source_id, {})

        # Determine classification
        # Check source_id pattern first
        src_class = classify_id(source_id)
        doc_class = classify_id(doc_id)
        event_class = classify_id(ev["event_id"])

        # Check if the source has a real URL
        source_path = source.get("source_path", "")
        canonical_url = doc.get("canonical_url", "")

        is_real_url = (
            source_path.startswith("http://") or source_path.startswith("https://")
        ) and (
            canonical_url.startswith("http://") or canonical_url.startswith("https://")
        )

        # Check if there's a retrieval event matching this document's URL
        has_retrieval = any(
            r.get("requested_url", "") == canonical_url or r.get("final_url", "") == canonical_url
            for r in retrieval_events
        )

        # Final classification
        if src_class == "SYNTHETIC_TEST" or doc_class == "SYNTHETIC_TEST" or event_class == "SYNTHETIC_TEST":
            classification = "SYNTHETIC_TEST"
            synthetic_count += 1
        elif src_class == "CANONICAL_FIXTURE" or doc_class == "CANONICAL_FIXTURE":
            classification = "CANONICAL_FIXTURE"
            canonical_count += 1
        elif is_real_url and has_retrieval:
            classification = "REAL_OFFICIAL_SOURCE"
            real_count += 1
        elif is_real_url:
            # Has real URL but no matching retrieval event — still real source
            classification = "REAL_OFFICIAL_SOURCE"
            real_count += 1
        else:
            classification = "UNKNOWN"
            unknown_count += 1

        classifications.append({
            "io_id": io_id_str,
            "event_id": ev["event_id"],
            "event_type": ev.get("event_type", ""),
            "source_id": source_id,
            "source_name": source.get("source_id", ""),
            "source_path": source_path[:80],
            "canonical_url": canonical_url[:80],
            "classification": classification,
        })

    return classifications, {
        "REAL_OFFICIAL_SOURCE": real_count,
        "SYNTHETIC_TEST": synthetic_count,
        "CANONICAL_FIXTURE": canonical_count,
        "UNKNOWN": unknown_count,
        "TOTAL": len(classifications),
    }


def main():
    store_root = sys.argv[1] if len(sys.argv) > 1 else "corpus_100_store"
    print(f"\n{'='*70}")
    print(f"V2-Real §2 — Audit of {store_root}")
    print(f"{'='*70}")

    classifications, counts = audit_store(store_root)

    print(f"\n--- Classification Summary ---")
    for k, v in counts.items():
        pct = (v / counts["TOTAL"] * 100) if counts["TOTAL"] else 0
        print(f"  {k:<25} {v:>5}  ({pct:.1f}%)")

    # Group by event_type
    print(f"\n--- By Event Type ---")
    by_type = defaultdict(lambda: Counter())
    for c in classifications:
        by_type[c["event_type"]][c["classification"]] += 1
    for et, dist in sorted(by_type.items()):
        print(f"  {et}:")
        for cls, n in dist.most_common():
            print(f"    {cls:<25} {n:>5}")

    # Group REAL by source
    print(f"\n--- REAL_OFFICIAL_SOURCE by source ---")
    real_by_source = defaultdict(list)
    for c in classifications:
        if c["classification"] == "REAL_OFFICIAL_SOURCE":
            real_by_source[c["source_id"]].append(c["io_id"])
    for src, ios in sorted(real_by_source.items(), key=lambda x: -len(x[1])):
        print(f"  {src:<35} {len(ios):>3} IOs")

    # Save full audit
    out_path = Path(__file__).resolve().parent / "audit_111_results.json"
    with open(out_path, "w") as f:
        json.dump({
            "store_root": store_root,
            "counts": counts,
            "by_event_type": {k: dict(v) for k, v in by_type.items()},
            "real_by_source": {k: len(v) for k, v in real_by_source.items()},
            "classifications": classifications,
        }, f, indent=2, default=str)
    print(f"\n  Full audit saved to: {out_path}")

    return counts


if __name__ == "__main__":
    counts = main()
    # Exit code based on whether we have ≥100 REAL
    if counts["REAL_OFFICIAL_SOURCE"] >= 100:
        print(f"\n  ✓ PASS: ≥100 REAL_OFFICIAL_SOURCE IOs")
        sys.exit(0)
    else:
        print(f"\n  ✗ FAIL: only {counts['REAL_OFFICIAL_SOURCE']} REAL_OFFICIAL_SOURCE (need ≥100)")
        sys.exit(1)
